export const NAME_IDENTIFIER_TYPE = {
  LEGAL_PERSON_NAME_TYPE_CODE_LEGL: 'Legal',
  LEGAL_PERSON_NAME_TYPE_CODE_SHRT: 'Short',
  LEGAL_PERSON_NAME_TYPE_CODE_TRAD: 'Trading',
  LEGAL_PERSON_NAME_TYPE_CODE_MISC: 'Misc',
};
