export const NATIONAL_IDENTIFIER_TYPE = {
  NATIONAL_IDENTIFIER_TYPE_CODE_MISC: 'MISC',
  NATIONAL_IDENTIFIER_TYPE_CODE_ARNU: 'ARNU',
  NATIONAL_IDENTIFIER_TYPE_CODE_CCPT: 'Passport',
  NATIONAL_IDENTIFIER_TYPE_CODE_RAID: 'RAID',
  NATIONAL_IDENTIFIER_TYPE_CODE_DRLC: "Driver's License",
  NATIONAL_IDENTIFIER_TYPE_CODE_FIIN: 'FIIN',
  NATIONAL_IDENTIFIER_TYPE_CODE_TXID: 'Tax ID',
  NATIONAL_IDENTIFIER_TYPE_CODE_SOCS: 'Social Security',
  NATIONAL_IDENTIFIER_TYPE_CODE_IDCD: 'Identity Card',
  NATIONAL_IDENTIFIER_TYPE_CODE_LEIX: 'LEI',
};
