// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: gds/models/v1/contacts.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contact contains a unique email address and information about a TRISA member.
type Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique email address for this contact
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // used to address the email
	// List of VASP IDs that the contact is included in
	Vasps []string `protobuf:"bytes,3,rep,name=vasps,proto3" json:"vasps,omitempty"`
	// Token for email verification
	Verified bool   `protobuf:"varint,4,opt,name=verified,proto3" json:"verified,omitempty"`
	Token    string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	// Email audit log
	EmailLog []*EmailLogEntry `protobuf:"bytes,6,rep,name=email_log,json=emailLog,proto3" json:"email_log,omitempty"`
	// RFC3339 Timestamp for when the contact was verified
	VerifiedOn string `protobuf:"bytes,7,opt,name=verified_on,json=verifiedOn,proto3" json:"verified_on,omitempty"`
	// Logging information timestamps
	Created  string `protobuf:"bytes,8,opt,name=created,proto3" json:"created,omitempty"`
	Modified string `protobuf:"bytes,9,opt,name=modified,proto3" json:"modified,omitempty"`
}

func (x *Contact) Reset() {
	*x = Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gds_models_v1_contacts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_contacts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_contacts_proto_rawDescGZIP(), []int{0}
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetVasps() []string {
	if x != nil {
		return x.Vasps
	}
	return nil
}

func (x *Contact) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Contact) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Contact) GetEmailLog() []*EmailLogEntry {
	if x != nil {
		return x.EmailLog
	}
	return nil
}

func (x *Contact) GetVerifiedOn() string {
	if x != nil {
		return x.VerifiedOn
	}
	return ""
}

func (x *Contact) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Contact) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

// Email refers to a unique email address that can be used across multiple TRISA
// contacts inside of a VASP record. The email structure stores the verification token
// as well as the most current name referring to the contact for addressing emails.
type Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"` // Unique email address for this contact (also used for the key)
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`   // Used to address the email, should be sent to most current name
	// List of VASP IDs that the contact is included in
	Vasps []string `protobuf:"bytes,3,rep,name=vasps,proto3" json:"vasps,omitempty"`
	// Token for email verification
	Verified bool   `protobuf:"varint,4,opt,name=verified,proto3" json:"verified,omitempty"`
	Token    string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	// RFC3339 Timestamp for when the contact was verified
	VerifiedOn string `protobuf:"bytes,6,opt,name=verified_on,json=verifiedOn,proto3" json:"verified_on,omitempty"`
	// A log of all emails sent to this contact record
	SendLog []*EmailLogEntry `protobuf:"bytes,13,rep,name=send_log,json=sendLog,proto3" json:"send_log,omitempty"`
	// Logging information timestamps
	Created  string `protobuf:"bytes,14,opt,name=created,proto3" json:"created,omitempty"`
	Modified string `protobuf:"bytes,15,opt,name=modified,proto3" json:"modified,omitempty"`
}

func (x *Email) Reset() {
	*x = Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gds_models_v1_contacts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_contacts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_contacts_proto_rawDescGZIP(), []int{1}
}

func (x *Email) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Email) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Email) GetVasps() []string {
	if x != nil {
		return x.Vasps
	}
	return nil
}

func (x *Email) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Email) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Email) GetVerifiedOn() string {
	if x != nil {
		return x.VerifiedOn
	}
	return ""
}

func (x *Email) GetSendLog() []*EmailLogEntry {
	if x != nil {
		return x.SendLog
	}
	return nil
}

func (x *Email) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Email) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

// EmailLogEntry contains information about a single email message that was sent.
// The key of the email log entry is the recipient + the timestamp of the email.
type EmailLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// RFC3339 timestamp
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Reason why the email was sent
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Subject line of the email
	Subject string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	// Email address of the recipient
	Recipient string `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (x *EmailLogEntry) Reset() {
	*x = EmailLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gds_models_v1_contacts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailLogEntry) ProtoMessage() {}

func (x *EmailLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_contacts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailLogEntry.ProtoReflect.Descriptor instead.
func (*EmailLogEntry) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_contacts_proto_rawDescGZIP(), []int{2}
}

func (x *EmailLogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *EmailLogEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EmailLogEntry) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailLogEntry) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

var File_gds_models_v1_contacts_proto protoreflect.FileDescriptor

var file_gds_models_v1_contacts_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x67, 0x64, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x67, 0x64, 0x73, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x8d, 0x02,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x73, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x73, 0x70, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x39, 0x0a, 0x09, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x67, 0x64, 0x73, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x4c, 0x6f, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x4f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x89, 0x02,
	0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x73, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x73, 0x70, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x4f, 0x6e, 0x12, 0x37, 0x0a, 0x08, 0x73, 0x65,
	0x6e, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x64, 0x73, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x65, 0x6e, 0x64,
	0x4c, 0x6f, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x7d, 0x0a, 0x0d, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x69, 0x73, 0x61, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x2f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gds_models_v1_contacts_proto_rawDescOnce sync.Once
	file_gds_models_v1_contacts_proto_rawDescData = file_gds_models_v1_contacts_proto_rawDesc
)

func file_gds_models_v1_contacts_proto_rawDescGZIP() []byte {
	file_gds_models_v1_contacts_proto_rawDescOnce.Do(func() {
		file_gds_models_v1_contacts_proto_rawDescData = protoimpl.X.CompressGZIP(file_gds_models_v1_contacts_proto_rawDescData)
	})
	return file_gds_models_v1_contacts_proto_rawDescData
}

var file_gds_models_v1_contacts_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gds_models_v1_contacts_proto_goTypes = []interface{}{
	(*Contact)(nil),       // 0: gds.models.v1.Contact
	(*Email)(nil),         // 1: gds.models.v1.Email
	(*EmailLogEntry)(nil), // 2: gds.models.v1.EmailLogEntry
}
var file_gds_models_v1_contacts_proto_depIdxs = []int32{
	2, // 0: gds.models.v1.Contact.email_log:type_name -> gds.models.v1.EmailLogEntry
	2, // 1: gds.models.v1.Email.send_log:type_name -> gds.models.v1.EmailLogEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gds_models_v1_contacts_proto_init() }
func file_gds_models_v1_contacts_proto_init() {
	if File_gds_models_v1_contacts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gds_models_v1_contacts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gds_models_v1_contacts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gds_models_v1_contacts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gds_models_v1_contacts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gds_models_v1_contacts_proto_goTypes,
		DependencyIndexes: file_gds_models_v1_contacts_proto_depIdxs,
		MessageInfos:      file_gds_models_v1_contacts_proto_msgTypes,
	}.Build()
	File_gds_models_v1_contacts_proto = out.File
	file_gds_models_v1_contacts_proto_rawDesc = nil
	file_gds_models_v1_contacts_proto_goTypes = nil
	file_gds_models_v1_contacts_proto_depIdxs = nil
}
