// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: gds/models/v1/models.proto

package models

import (
	v1beta1 "github.com/trisacrypto/trisa/pkg/trisa/gds/models/v1beta1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificateState int32

const (
	CertificateState_ISSUED  CertificateState = 0
	CertificateState_EXPIRED CertificateState = 1
	CertificateState_REVOKED CertificateState = 2
)

// Enum value maps for CertificateState.
var (
	CertificateState_name = map[int32]string{
		0: "ISSUED",
		1: "EXPIRED",
		2: "REVOKED",
	}
	CertificateState_value = map[string]int32{
		"ISSUED":  0,
		"EXPIRED": 1,
		"REVOKED": 2,
	}
)

func (x CertificateState) Enum() *CertificateState {
	p := new(CertificateState)
	*p = x
	return p
}

func (x CertificateState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateState) Descriptor() protoreflect.EnumDescriptor {
	return file_gds_models_v1_models_proto_enumTypes[0].Descriptor()
}

func (CertificateState) Type() protoreflect.EnumType {
	return &file_gds_models_v1_models_proto_enumTypes[0]
}

func (x CertificateState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateState.Descriptor instead.
func (CertificateState) EnumDescriptor() ([]byte, []int) {
	return file_gds_models_v1_models_proto_rawDescGZIP(), []int{0}
}

type CertificateRequestState int32

const (
	CertificateRequestState_INITIALIZED     CertificateRequestState = 0
	CertificateRequestState_READY_TO_SUBMIT CertificateRequestState = 1
	CertificateRequestState_PROCESSING      CertificateRequestState = 2
	CertificateRequestState_DOWNLOADING     CertificateRequestState = 3
	CertificateRequestState_DOWNLOADED      CertificateRequestState = 4
	CertificateRequestState_COMPLETED       CertificateRequestState = 5
	CertificateRequestState_CR_REJECTED     CertificateRequestState = 6
	CertificateRequestState_CR_ERRORED      CertificateRequestState = 7
)

// Enum value maps for CertificateRequestState.
var (
	CertificateRequestState_name = map[int32]string{
		0: "INITIALIZED",
		1: "READY_TO_SUBMIT",
		2: "PROCESSING",
		3: "DOWNLOADING",
		4: "DOWNLOADED",
		5: "COMPLETED",
		6: "CR_REJECTED",
		7: "CR_ERRORED",
	}
	CertificateRequestState_value = map[string]int32{
		"INITIALIZED":     0,
		"READY_TO_SUBMIT": 1,
		"PROCESSING":      2,
		"DOWNLOADING":     3,
		"DOWNLOADED":      4,
		"COMPLETED":       5,
		"CR_REJECTED":     6,
		"CR_ERRORED":      7,
	}
)

func (x CertificateRequestState) Enum() *CertificateRequestState {
	p := new(CertificateRequestState)
	*p = x
	return p
}

func (x CertificateRequestState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateRequestState) Descriptor() protoreflect.EnumDescriptor {
	return file_gds_models_v1_models_proto_enumTypes[1].Descriptor()
}

func (CertificateRequestState) Type() protoreflect.EnumType {
	return &file_gds_models_v1_models_proto_enumTypes[1]
}

func (x CertificateRequestState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateRequestState.Descriptor instead.
func (CertificateRequestState) EnumDescriptor() ([]byte, []int) {
	return file_gds_models_v1_models_proto_rawDescGZIP(), []int{1}
}

// Certificate embeds a TRISA Certificate into a record that can be stored in the
// database for certificate management.
type Certificate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique identifier generated by the directory service for storage
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// CertificateRequest that this certificate is associated with
	Request string `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	// VASP that this certificate belongs to
	Vasp string `protobuf:"bytes,3,opt,name=vasp,proto3" json:"vasp,omitempty"`
	// Current status of the certificate
	Status CertificateState `protobuf:"varint,4,opt,name=status,proto3,enum=gds.models.v1.CertificateState" json:"status,omitempty"`
	// Certificate details
	Details       *v1beta1.Certificate `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_gds_models_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Certificate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Certificate) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *Certificate) GetVasp() string {
	if x != nil {
		return x.Vasp
	}
	return ""
}

func (x *Certificate) GetStatus() CertificateState {
	if x != nil {
		return x.Status
	}
	return CertificateState_ISSUED
}

func (x *Certificate) GetDetails() *v1beta1.Certificate {
	if x != nil {
		return x.Details
	}
	return nil
}

// Certificate requests are maintained separately from the VASP record since they should
// not be replicated. E.g. every directory process is responsible for certificate
// issuance and only public keys and certificate metadata should be exchanged between
// directories.
type CertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique identifier generated by the directory service, should be a globally
	// unique identifier generated by the replica specified in requesting_replica.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// VASP information for the request
	Vasp       string `protobuf:"bytes,2,opt,name=vasp,proto3" json:"vasp,omitempty"`
	CommonName string `protobuf:"bytes,3,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	// Request pipeline status
	Status CertificateRequestState `protobuf:"varint,4,opt,name=status,proto3,enum=gds.models.v1.CertificateRequestState" json:"status,omitempty"`
	// Sectigo create single certificate batch metadata
	AuthorityId  int64  `protobuf:"varint,5,opt,name=authority_id,json=authorityId,proto3" json:"authority_id,omitempty"`
	BatchId      int64  `protobuf:"varint,6,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	BatchName    string `protobuf:"bytes,7,opt,name=batch_name,json=batchName,proto3" json:"batch_name,omitempty"`
	BatchStatus  string `protobuf:"bytes,8,opt,name=batch_status,json=batchStatus,proto3" json:"batch_status,omitempty"`
	OrderNumber  int64  `protobuf:"varint,9,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	CreationDate string `protobuf:"bytes,10,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	Profile      string `protobuf:"bytes,11,opt,name=profile,proto3" json:"profile,omitempty"`
	RejectReason string `protobuf:"bytes,12,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	// Generic parameters used for making requests to certificate issuing services
	Params map[string]string `protobuf:"bytes,13,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional list of alternate dns names in addition to the common name
	DnsNames []string `protobuf:"bytes,14,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	// Logging information timestamps
	Created  string `protobuf:"bytes,15,opt,name=created,proto3" json:"created,omitempty"`
	Modified string `protobuf:"bytes,16,opt,name=modified,proto3" json:"modified,omitempty"`
	// Log of historical request states
	AuditLog []*CertificateRequestLogEntry `protobuf:"bytes,17,rep,name=audit_log,json=auditLog,proto3" json:"audit_log,omitempty"`
	// The certificate ID downloaded from the request, if completed successfully
	Certificate string `protobuf:"bytes,18,opt,name=certificate,proto3" json:"certificate,omitempty"`
	// Webhook for certificate delivery
	Webhook string `protobuf:"bytes,19,opt,name=webhook,proto3" json:"webhook,omitempty"`
	// Don't deliver certificates by email
	NoEmailDelivery bool `protobuf:"varint,20,opt,name=no_email_delivery,json=noEmailDelivery,proto3" json:"no_email_delivery,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CertificateRequest) Reset() {
	*x = CertificateRequest{}
	mi := &file_gds_models_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequest) ProtoMessage() {}

func (x *CertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequest.ProtoReflect.Descriptor instead.
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CertificateRequest) GetVasp() string {
	if x != nil {
		return x.Vasp
	}
	return ""
}

func (x *CertificateRequest) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *CertificateRequest) GetStatus() CertificateRequestState {
	if x != nil {
		return x.Status
	}
	return CertificateRequestState_INITIALIZED
}

func (x *CertificateRequest) GetAuthorityId() int64 {
	if x != nil {
		return x.AuthorityId
	}
	return 0
}

func (x *CertificateRequest) GetBatchId() int64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *CertificateRequest) GetBatchName() string {
	if x != nil {
		return x.BatchName
	}
	return ""
}

func (x *CertificateRequest) GetBatchStatus() string {
	if x != nil {
		return x.BatchStatus
	}
	return ""
}

func (x *CertificateRequest) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *CertificateRequest) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *CertificateRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *CertificateRequest) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *CertificateRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *CertificateRequest) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

func (x *CertificateRequest) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *CertificateRequest) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

func (x *CertificateRequest) GetAuditLog() []*CertificateRequestLogEntry {
	if x != nil {
		return x.AuditLog
	}
	return nil
}

func (x *CertificateRequest) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *CertificateRequest) GetWebhook() string {
	if x != nil {
		return x.Webhook
	}
	return ""
}

func (x *CertificateRequest) GetNoEmailDelivery() bool {
	if x != nil {
		return x.NoEmailDelivery
	}
	return false
}

// CertificateRequestLogEntry contains information about the state of a certificate request.
type CertificateRequestLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFC3339 timestamp
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Previous request state (handled internally) and current request state
	PreviousState CertificateRequestState `protobuf:"varint,2,opt,name=previous_state,json=previousState,proto3,enum=gds.models.v1.CertificateRequestState" json:"previous_state,omitempty"`
	CurrentState  CertificateRequestState `protobuf:"varint,3,opt,name=current_state,json=currentState,proto3,enum=gds.models.v1.CertificateRequestState" json:"current_state,omitempty"`
	// Description of the current state of the certificate request
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Email address of the Admin who made the state change, "automated" if the state
	// change happened automatically
	Source        string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateRequestLogEntry) Reset() {
	*x = CertificateRequestLogEntry{}
	mi := &file_gds_models_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRequestLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequestLogEntry) ProtoMessage() {}

func (x *CertificateRequestLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequestLogEntry.ProtoReflect.Descriptor instead.
func (*CertificateRequestLogEntry) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *CertificateRequestLogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *CertificateRequestLogEntry) GetPreviousState() CertificateRequestState {
	if x != nil {
		return x.PreviousState
	}
	return CertificateRequestState_INITIALIZED
}

func (x *CertificateRequestLogEntry) GetCurrentState() CertificateRequestState {
	if x != nil {
		return x.CurrentState
	}
	return CertificateRequestState_INITIALIZED
}

func (x *CertificateRequestLogEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CertificateRequestLogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// GDSExtraData contains all GDS-specific extra data for a VASP record.
type GDSExtraData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Temporary: verification token for light weight authentication for verification
	// TODO: replace with admin API that uses authentication
	AdminVerificationToken string `protobuf:"bytes,1,opt,name=admin_verification_token,json=adminVerificationToken,proto3" json:"admin_verification_token,omitempty"`
	// Audit log which records events relevant to a VASP
	AuditLog []*AuditLogEntry `protobuf:"bytes,2,rep,name=audit_log,json=auditLog,proto3" json:"audit_log,omitempty"`
	// Record of all the review notes associated with this VASP
	ReviewNotes map[string]*ReviewNote `protobuf:"bytes,3,rep,name=review_notes,json=reviewNotes,proto3" json:"review_notes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Certificate requests associated with this VASP
	CertificateRequests []string `protobuf:"bytes,4,rep,name=certificate_requests,json=certificateRequests,proto3" json:"certificate_requests,omitempty"`
	// Certificate IDs associated with this VASP
	Certificates []string `protobuf:"bytes,5,rep,name=certificates,proto3" json:"certificates,omitempty"`
	// Log which records emails sent to the TRISA admins regarding this VASP
	EmailLog      []*EmailLogEntry `protobuf:"bytes,6,rep,name=email_log,json=emailLog,proto3" json:"email_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GDSExtraData) Reset() {
	*x = GDSExtraData{}
	mi := &file_gds_models_v1_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GDSExtraData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GDSExtraData) ProtoMessage() {}

func (x *GDSExtraData) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GDSExtraData.ProtoReflect.Descriptor instead.
func (*GDSExtraData) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_models_proto_rawDescGZIP(), []int{3}
}

func (x *GDSExtraData) GetAdminVerificationToken() string {
	if x != nil {
		return x.AdminVerificationToken
	}
	return ""
}

func (x *GDSExtraData) GetAuditLog() []*AuditLogEntry {
	if x != nil {
		return x.AuditLog
	}
	return nil
}

func (x *GDSExtraData) GetReviewNotes() map[string]*ReviewNote {
	if x != nil {
		return x.ReviewNotes
	}
	return nil
}

func (x *GDSExtraData) GetCertificateRequests() []string {
	if x != nil {
		return x.CertificateRequests
	}
	return nil
}

func (x *GDSExtraData) GetCertificates() []string {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *GDSExtraData) GetEmailLog() []*EmailLogEntry {
	if x != nil {
		return x.EmailLog
	}
	return nil
}

// AuditLogEntry contains information about an event relevant to a VASP
// (e.g., verification state changes).
type AuditLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFC3339 timestamp
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Previous verification state (handled internally) and current verification state
	PreviousState v1beta1.VerificationState `protobuf:"varint,2,opt,name=previous_state,json=previousState,proto3,enum=trisa.gds.models.v1beta1.VerificationState" json:"previous_state,omitempty"`
	CurrentState  v1beta1.VerificationState `protobuf:"varint,3,opt,name=current_state,json=currentState,proto3,enum=trisa.gds.models.v1beta1.VerificationState" json:"current_state,omitempty"`
	// Description which can be supplied by the Admin when making a state change
	// (e.g., "resent emails")
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Email address of the Admin who made the state change, "automated" if the state
	// change happened automatically
	Source        string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEntry) Reset() {
	*x = AuditLogEntry{}
	mi := &file_gds_models_v1_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEntry) ProtoMessage() {}

func (x *AuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEntry.ProtoReflect.Descriptor instead.
func (*AuditLogEntry) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_models_proto_rawDescGZIP(), []int{4}
}

func (x *AuditLogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AuditLogEntry) GetPreviousState() v1beta1.VerificationState {
	if x != nil {
		return x.PreviousState
	}
	return v1beta1.VerificationState(0)
}

func (x *AuditLogEntry) GetCurrentState() v1beta1.VerificationState {
	if x != nil {
		return x.CurrentState
	}
	return v1beta1.VerificationState(0)
}

func (x *AuditLogEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuditLogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ReviewNote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the note
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// RFC3339 timestamps representing when the note was created, modified
	Created  string `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Modified string `protobuf:"bytes,3,opt,name=modified,proto3" json:"modified,omitempty"`
	// Email address of the author and the last editor
	Author string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Editor string `protobuf:"bytes,5,opt,name=editor,proto3" json:"editor,omitempty"`
	// Actual text in the note
	Text          string `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewNote) Reset() {
	*x = ReviewNote{}
	mi := &file_gds_models_v1_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewNote) ProtoMessage() {}

func (x *ReviewNote) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewNote.ProtoReflect.Descriptor instead.
func (*ReviewNote) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_models_proto_rawDescGZIP(), []int{5}
}

func (x *ReviewNote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReviewNote) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *ReviewNote) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

func (x *ReviewNote) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ReviewNote) GetEditor() string {
	if x != nil {
		return x.Editor
	}
	return ""
}

func (x *ReviewNote) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// GDSContactExtraData contains all GDS-specific extra data for a Contact record.
type GDSContactExtraData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for email verification
	Verified bool   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Email audit log
	EmailLog      []*EmailLogEntry `protobuf:"bytes,3,rep,name=email_log,json=emailLog,proto3" json:"email_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GDSContactExtraData) Reset() {
	*x = GDSContactExtraData{}
	mi := &file_gds_models_v1_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GDSContactExtraData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GDSContactExtraData) ProtoMessage() {}

func (x *GDSContactExtraData) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GDSContactExtraData.ProtoReflect.Descriptor instead.
func (*GDSContactExtraData) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_models_proto_rawDescGZIP(), []int{6}
}

func (x *GDSContactExtraData) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *GDSContactExtraData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GDSContactExtraData) GetEmailLog() []*EmailLogEntry {
	if x != nil {
		return x.EmailLog
	}
	return nil
}

// EmailLogEntry contains information about a single email message that was sent.
type EmailLogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFC3339 timestamp
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Reason why the email was sent
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Subject line of the email
	Subject string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	// Email address of the recipient
	Recipient     string `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailLogEntry) Reset() {
	*x = EmailLogEntry{}
	mi := &file_gds_models_v1_models_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailLogEntry) ProtoMessage() {}

func (x *EmailLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_models_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailLogEntry.ProtoReflect.Descriptor instead.
func (*EmailLogEntry) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_models_proto_rawDescGZIP(), []int{7}
}

func (x *EmailLogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *EmailLogEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EmailLogEntry) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailLogEntry) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

// Contact contains a unique email address and information about a TRISA member.
type Contact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique email address for this contact
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // used to address the email
	// List of VASPs that the contact is included in
	Vasps []string `protobuf:"bytes,3,rep,name=vasps,proto3" json:"vasps,omitempty"`
	// Token for email verification
	Verified bool   `protobuf:"varint,4,opt,name=verified,proto3" json:"verified,omitempty"`
	Token    string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	// Email audit log
	EmailLog []*EmailLogEntry `protobuf:"bytes,6,rep,name=email_log,json=emailLog,proto3" json:"email_log,omitempty"`
	// RFC3339 Timestamp for when the contact was verified
	VerifiedOn string `protobuf:"bytes,7,opt,name=verified_on,json=verifiedOn,proto3" json:"verified_on,omitempty"`
	// Logging information timestamps
	Created       string `protobuf:"bytes,8,opt,name=created,proto3" json:"created,omitempty"`
	Modified      string `protobuf:"bytes,9,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_gds_models_v1_models_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_models_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_models_proto_rawDescGZIP(), []int{8}
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetVasps() []string {
	if x != nil {
		return x.Vasps
	}
	return nil
}

func (x *Contact) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Contact) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Contact) GetEmailLog() []*EmailLogEntry {
	if x != nil {
		return x.EmailLog
	}
	return nil
}

func (x *Contact) GetVerifiedOn() string {
	if x != nil {
		return x.VerifiedOn
	}
	return ""
}

func (x *Contact) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Contact) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

// Implements a protocol buffer struct for state managed pagination. This struct will be
// marshaled into a url-safe base64 encoded string and sent to the user as the
// next_page_token. The server should decode this struct to determine where to continue
// iteration for the next page. Note that the server should check to make sure the page
// size in the cursor matches the page size in the request.
// See https://cloud.google.com/apis/design/design_patterns#list_pagination for more.
type PageCursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // the number of results returned on each iteration.
	NextVasp      string                 `protobuf:"bytes,2,opt,name=next_vasp,json=nextVasp,proto3" json:"next_vasp,omitempty"`  // the VASP id to start the iteration from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageCursor) Reset() {
	*x = PageCursor{}
	mi := &file_gds_models_v1_models_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageCursor) ProtoMessage() {}

func (x *PageCursor) ProtoReflect() protoreflect.Message {
	mi := &file_gds_models_v1_models_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageCursor.ProtoReflect.Descriptor instead.
func (*PageCursor) Descriptor() ([]byte, []int) {
	return file_gds_models_v1_models_proto_rawDescGZIP(), []int{9}
}

func (x *PageCursor) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageCursor) GetNextVasp() string {
	if x != nil {
		return x.NextVasp
	}
	return ""
}

var File_gds_models_v1_models_proto protoreflect.FileDescriptor

const file_gds_models_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1agds/models/v1/models.proto\x12\rgds.models.v1\x1a!trisa/gds/models/v1beta1/ca.proto\x1a%trisa/gds/models/v1beta1/models.proto\"\xc5\x01\n" +
	"\vCertificate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\arequest\x18\x02 \x01(\tR\arequest\x12\x12\n" +
	"\x04vasp\x18\x03 \x01(\tR\x04vasp\x127\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1f.gds.models.v1.CertificateStateR\x06status\x12?\n" +
	"\adetails\x18\x05 \x01(\v2%.trisa.gds.models.v1beta1.CertificateR\adetails\"\xa5\x06\n" +
	"\x12CertificateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04vasp\x18\x02 \x01(\tR\x04vasp\x12\x1f\n" +
	"\vcommon_name\x18\x03 \x01(\tR\n" +
	"commonName\x12>\n" +
	"\x06status\x18\x04 \x01(\x0e2&.gds.models.v1.CertificateRequestStateR\x06status\x12!\n" +
	"\fauthority_id\x18\x05 \x01(\x03R\vauthorityId\x12\x19\n" +
	"\bbatch_id\x18\x06 \x01(\x03R\abatchId\x12\x1d\n" +
	"\n" +
	"batch_name\x18\a \x01(\tR\tbatchName\x12!\n" +
	"\fbatch_status\x18\b \x01(\tR\vbatchStatus\x12!\n" +
	"\forder_number\x18\t \x01(\x03R\vorderNumber\x12#\n" +
	"\rcreation_date\x18\n" +
	" \x01(\tR\fcreationDate\x12\x18\n" +
	"\aprofile\x18\v \x01(\tR\aprofile\x12#\n" +
	"\rreject_reason\x18\f \x01(\tR\frejectReason\x12E\n" +
	"\x06params\x18\r \x03(\v2-.gds.models.v1.CertificateRequest.ParamsEntryR\x06params\x12\x1b\n" +
	"\tdns_names\x18\x0e \x03(\tR\bdnsNames\x12\x18\n" +
	"\acreated\x18\x0f \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\x10 \x01(\tR\bmodified\x12F\n" +
	"\taudit_log\x18\x11 \x03(\v2).gds.models.v1.CertificateRequestLogEntryR\bauditLog\x12 \n" +
	"\vcertificate\x18\x12 \x01(\tR\vcertificate\x12\x18\n" +
	"\awebhook\x18\x13 \x01(\tR\awebhook\x12*\n" +
	"\x11no_email_delivery\x18\x14 \x01(\bR\x0fnoEmailDelivery\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x02\n" +
	"\x1aCertificateRequestLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12M\n" +
	"\x0eprevious_state\x18\x02 \x01(\x0e2&.gds.models.v1.CertificateRequestStateR\rpreviousState\x12K\n" +
	"\rcurrent_state\x18\x03 \x01(\x0e2&.gds.models.v1.CertificateRequestStateR\fcurrentState\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\xc1\x03\n" +
	"\fGDSExtraData\x128\n" +
	"\x18admin_verification_token\x18\x01 \x01(\tR\x16adminVerificationToken\x129\n" +
	"\taudit_log\x18\x02 \x03(\v2\x1c.gds.models.v1.AuditLogEntryR\bauditLog\x12O\n" +
	"\freview_notes\x18\x03 \x03(\v2,.gds.models.v1.GDSExtraData.ReviewNotesEntryR\vreviewNotes\x121\n" +
	"\x14certificate_requests\x18\x04 \x03(\tR\x13certificateRequests\x12\"\n" +
	"\fcertificates\x18\x05 \x03(\tR\fcertificates\x129\n" +
	"\temail_log\x18\x06 \x03(\v2\x1c.gds.models.v1.EmailLogEntryR\bemailLog\x1aY\n" +
	"\x10ReviewNotesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.gds.models.v1.ReviewNoteR\x05value:\x028\x01\"\x8d\x02\n" +
	"\rAuditLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12R\n" +
	"\x0eprevious_state\x18\x02 \x01(\x0e2+.trisa.gds.models.v1beta1.VerificationStateR\rpreviousState\x12P\n" +
	"\rcurrent_state\x18\x03 \x01(\x0e2+.trisa.gds.models.v1beta1.VerificationStateR\fcurrentState\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\x96\x01\n" +
	"\n" +
	"ReviewNote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\x03 \x01(\tR\bmodified\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x16\n" +
	"\x06editor\x18\x05 \x01(\tR\x06editor\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\"\x82\x01\n" +
	"\x13GDSContactExtraData\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x129\n" +
	"\temail_log\x18\x03 \x03(\v2\x1c.gds.models.v1.EmailLogEntryR\bemailLog\"}\n" +
	"\rEmailLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\tR\trecipient\"\x8d\x02\n" +
	"\aContact\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05vasps\x18\x03 \x03(\tR\x05vasps\x12\x1a\n" +
	"\bverified\x18\x04 \x01(\bR\bverified\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x129\n" +
	"\temail_log\x18\x06 \x03(\v2\x1c.gds.models.v1.EmailLogEntryR\bemailLog\x12\x1f\n" +
	"\vverified_on\x18\a \x01(\tR\n" +
	"verifiedOn\x12\x18\n" +
	"\acreated\x18\b \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\t \x01(\tR\bmodified\"F\n" +
	"\n" +
	"PageCursor\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tnext_vasp\x18\x02 \x01(\tR\bnextVasp*8\n" +
	"\x10CertificateState\x12\n" +
	"\n" +
	"\x06ISSUED\x10\x00\x12\v\n" +
	"\aEXPIRED\x10\x01\x12\v\n" +
	"\aREVOKED\x10\x02*\xa0\x01\n" +
	"\x17CertificateRequestState\x12\x0f\n" +
	"\vINITIALIZED\x10\x00\x12\x13\n" +
	"\x0fREADY_TO_SUBMIT\x10\x01\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x02\x12\x0f\n" +
	"\vDOWNLOADING\x10\x03\x12\x0e\n" +
	"\n" +
	"DOWNLOADED\x10\x04\x12\r\n" +
	"\tCOMPLETED\x10\x05\x12\x0f\n" +
	"\vCR_REJECTED\x10\x06\x12\x0e\n" +
	"\n" +
	"CR_ERRORED\x10\aB7Z5github.com/trisacrypto/directory/pkg/models/v1;modelsb\x06proto3"

var (
	file_gds_models_v1_models_proto_rawDescOnce sync.Once
	file_gds_models_v1_models_proto_rawDescData []byte
)

func file_gds_models_v1_models_proto_rawDescGZIP() []byte {
	file_gds_models_v1_models_proto_rawDescOnce.Do(func() {
		file_gds_models_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gds_models_v1_models_proto_rawDesc), len(file_gds_models_v1_models_proto_rawDesc)))
	})
	return file_gds_models_v1_models_proto_rawDescData
}

var file_gds_models_v1_models_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gds_models_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gds_models_v1_models_proto_goTypes = []any{
	(CertificateState)(0),              // 0: gds.models.v1.CertificateState
	(CertificateRequestState)(0),       // 1: gds.models.v1.CertificateRequestState
	(*Certificate)(nil),                // 2: gds.models.v1.Certificate
	(*CertificateRequest)(nil),         // 3: gds.models.v1.CertificateRequest
	(*CertificateRequestLogEntry)(nil), // 4: gds.models.v1.CertificateRequestLogEntry
	(*GDSExtraData)(nil),               // 5: gds.models.v1.GDSExtraData
	(*AuditLogEntry)(nil),              // 6: gds.models.v1.AuditLogEntry
	(*ReviewNote)(nil),                 // 7: gds.models.v1.ReviewNote
	(*GDSContactExtraData)(nil),        // 8: gds.models.v1.GDSContactExtraData
	(*EmailLogEntry)(nil),              // 9: gds.models.v1.EmailLogEntry
	(*Contact)(nil),                    // 10: gds.models.v1.Contact
	(*PageCursor)(nil),                 // 11: gds.models.v1.PageCursor
	nil,                                // 12: gds.models.v1.CertificateRequest.ParamsEntry
	nil,                                // 13: gds.models.v1.GDSExtraData.ReviewNotesEntry
	(*v1beta1.Certificate)(nil),        // 14: trisa.gds.models.v1beta1.Certificate
	(v1beta1.VerificationState)(0),     // 15: trisa.gds.models.v1beta1.VerificationState
}
var file_gds_models_v1_models_proto_depIdxs = []int32{
	0,  // 0: gds.models.v1.Certificate.status:type_name -> gds.models.v1.CertificateState
	14, // 1: gds.models.v1.Certificate.details:type_name -> trisa.gds.models.v1beta1.Certificate
	1,  // 2: gds.models.v1.CertificateRequest.status:type_name -> gds.models.v1.CertificateRequestState
	12, // 3: gds.models.v1.CertificateRequest.params:type_name -> gds.models.v1.CertificateRequest.ParamsEntry
	4,  // 4: gds.models.v1.CertificateRequest.audit_log:type_name -> gds.models.v1.CertificateRequestLogEntry
	1,  // 5: gds.models.v1.CertificateRequestLogEntry.previous_state:type_name -> gds.models.v1.CertificateRequestState
	1,  // 6: gds.models.v1.CertificateRequestLogEntry.current_state:type_name -> gds.models.v1.CertificateRequestState
	6,  // 7: gds.models.v1.GDSExtraData.audit_log:type_name -> gds.models.v1.AuditLogEntry
	13, // 8: gds.models.v1.GDSExtraData.review_notes:type_name -> gds.models.v1.GDSExtraData.ReviewNotesEntry
	9,  // 9: gds.models.v1.GDSExtraData.email_log:type_name -> gds.models.v1.EmailLogEntry
	15, // 10: gds.models.v1.AuditLogEntry.previous_state:type_name -> trisa.gds.models.v1beta1.VerificationState
	15, // 11: gds.models.v1.AuditLogEntry.current_state:type_name -> trisa.gds.models.v1beta1.VerificationState
	9,  // 12: gds.models.v1.GDSContactExtraData.email_log:type_name -> gds.models.v1.EmailLogEntry
	9,  // 13: gds.models.v1.Contact.email_log:type_name -> gds.models.v1.EmailLogEntry
	7,  // 14: gds.models.v1.GDSExtraData.ReviewNotesEntry.value:type_name -> gds.models.v1.ReviewNote
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_gds_models_v1_models_proto_init() }
func file_gds_models_v1_models_proto_init() {
	if File_gds_models_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gds_models_v1_models_proto_rawDesc), len(file_gds_models_v1_models_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gds_models_v1_models_proto_goTypes,
		DependencyIndexes: file_gds_models_v1_models_proto_depIdxs,
		EnumInfos:         file_gds_models_v1_models_proto_enumTypes,
		MessageInfos:      file_gds_models_v1_models_proto_msgTypes,
	}.Build()
	File_gds_models_v1_models_proto = out.File
	file_gds_models_v1_models_proto_goTypes = nil
	file_gds_models_v1_models_proto_depIdxs = nil
}
