// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: bff/models/v1/models.proto

package models

import (
	ivms101 "github.com/trisacrypto/trisa/pkg/ivms101"
	v1beta1 "github.com/trisacrypto/trisa/pkg/trisa/gds/models/v1beta1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttentionSeverity is used to indicate the importance of an attention message
type AttentionSeverity int32

const (
	AttentionSeverity_SUCCESS AttentionSeverity = 0
	AttentionSeverity_INFO    AttentionSeverity = 1
	AttentionSeverity_WARNING AttentionSeverity = 2
	AttentionSeverity_ALERT   AttentionSeverity = 3
)

// Enum value maps for AttentionSeverity.
var (
	AttentionSeverity_name = map[int32]string{
		0: "SUCCESS",
		1: "INFO",
		2: "WARNING",
		3: "ALERT",
	}
	AttentionSeverity_value = map[string]int32{
		"SUCCESS": 0,
		"INFO":    1,
		"WARNING": 2,
		"ALERT":   3,
	}
)

func (x AttentionSeverity) Enum() *AttentionSeverity {
	p := new(AttentionSeverity)
	*p = x
	return p
}

func (x AttentionSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttentionSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_bff_models_v1_models_proto_enumTypes[0].Descriptor()
}

func (AttentionSeverity) Type() protoreflect.EnumType {
	return &file_bff_models_v1_models_proto_enumTypes[0]
}

func (x AttentionSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttentionSeverity.Descriptor instead.
func (AttentionSeverity) EnumDescriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{0}
}

// AttentionAction is used to indicate the action that should be taken by the user in
// response to an attention message.
type AttentionAction int32

const (
	AttentionAction_NO_ACTION             AttentionAction = 0
	AttentionAction_START_REGISTRATION    AttentionAction = 1
	AttentionAction_COMPLETE_REGISTRATION AttentionAction = 2
	AttentionAction_SUBMIT_TESTNET        AttentionAction = 3
	AttentionAction_SUBMIT_MAINNET        AttentionAction = 4
	AttentionAction_VERIFY_EMAILS         AttentionAction = 5
	AttentionAction_RENEW_CERTIFICATE     AttentionAction = 6
	AttentionAction_CONTACT_SUPPORT       AttentionAction = 7
)

// Enum value maps for AttentionAction.
var (
	AttentionAction_name = map[int32]string{
		0: "NO_ACTION",
		1: "START_REGISTRATION",
		2: "COMPLETE_REGISTRATION",
		3: "SUBMIT_TESTNET",
		4: "SUBMIT_MAINNET",
		5: "VERIFY_EMAILS",
		6: "RENEW_CERTIFICATE",
		7: "CONTACT_SUPPORT",
	}
	AttentionAction_value = map[string]int32{
		"NO_ACTION":             0,
		"START_REGISTRATION":    1,
		"COMPLETE_REGISTRATION": 2,
		"SUBMIT_TESTNET":        3,
		"SUBMIT_MAINNET":        4,
		"VERIFY_EMAILS":         5,
		"RENEW_CERTIFICATE":     6,
		"CONTACT_SUPPORT":       7,
	}
)

func (x AttentionAction) Enum() *AttentionAction {
	p := new(AttentionAction)
	*p = x
	return p
}

func (x AttentionAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttentionAction) Descriptor() protoreflect.EnumDescriptor {
	return file_bff_models_v1_models_proto_enumTypes[1].Descriptor()
}

func (AttentionAction) Type() protoreflect.EnumType {
	return &file_bff_models_v1_models_proto_enumTypes[1]
}

func (x AttentionAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttentionAction.Descriptor instead.
func (AttentionAction) EnumDescriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{1}
}

// The Organization document contains VASP-specific information for a single VASP record
// in the directory service. This document differs in that it stores information
// relevant to the BFF and should not be used to duplicate storage in the directory.
type Organization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BFF Unique Identifier and Record Information
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl   string `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Domain    string `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	CreatedBy string `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// Directory Registrations for Lookups
	// TODO: populate these details in the Registration Endpoint
	Testnet *DirectoryRecord `protobuf:"bytes,10,opt,name=testnet,proto3" json:"testnet,omitempty"`
	Mainnet *DirectoryRecord `protobuf:"bytes,11,opt,name=mainnet,proto3" json:"mainnet,omitempty"`
	// Collaborators
	Collaborators map[string]*Collaborator `protobuf:"bytes,12,rep,name=collaborators,proto3" json:"collaborators,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Registration Form
	Registration *RegistrationForm `protobuf:"bytes,13,opt,name=registration,proto3" json:"registration,omitempty"`
	// Metadata as RFC3339Nano Timestamps
	Created       string `protobuf:"bytes,14,opt,name=created,proto3" json:"created,omitempty"`
	Modified      string `protobuf:"bytes,15,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_bff_models_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_bff_models_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *Organization) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Organization) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Organization) GetTestnet() *DirectoryRecord {
	if x != nil {
		return x.Testnet
	}
	return nil
}

func (x *Organization) GetMainnet() *DirectoryRecord {
	if x != nil {
		return x.Mainnet
	}
	return nil
}

func (x *Organization) GetCollaborators() map[string]*Collaborator {
	if x != nil {
		return x.Collaborators
	}
	return nil
}

func (x *Organization) GetRegistration() *RegistrationForm {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *Organization) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Organization) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

// A Collaborator is a user that is associated with an organization. Collaborators are
// uniquely identified by their email address and the Organization document they exist
// on. Therefore, it is possible for a user to exist as a collaborator on multiple
// organizations. The information in the Collaborator document is meant to be used by
// frontend applications to manage and display collaborators and their roles to the
// user, so the BFF should periodically keep this information up to date by syncing
// with the authentication service (e.g. Auth0).
type Collaborator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifiers used by the BFF
	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// User data cached from the authentication service
	UserId   string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name     string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Roles    []string `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	Verified bool     `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	// Metadata as RFC3339Nano Timestamps
	CreatedAt     string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    string `protobuf:"bytes,11,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	JoinedAt      string `protobuf:"bytes,12,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LastLogin     string `protobuf:"bytes,13,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	ExpiresAt     string `protobuf:"bytes,14,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collaborator) Reset() {
	*x = Collaborator{}
	mi := &file_bff_models_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collaborator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collaborator) ProtoMessage() {}

func (x *Collaborator) ProtoReflect() protoreflect.Message {
	mi := &file_bff_models_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collaborator.ProtoReflect.Descriptor instead.
func (*Collaborator) Descriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *Collaborator) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Collaborator) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Collaborator) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Collaborator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collaborator) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Collaborator) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Collaborator) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Collaborator) GetModifiedAt() string {
	if x != nil {
		return x.ModifiedAt
	}
	return ""
}

func (x *Collaborator) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *Collaborator) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

func (x *Collaborator) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// FormState contains the current state of an organization's registration form to
// enable a consistent user experience across multiple contexts.
type FormState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current 1-indexed step of the form
	Current int32 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	// If set, the form is completely filled out and ready to be submitted
	ReadyToSubmit bool `protobuf:"varint,2,opt,name=ready_to_submit,json=readyToSubmit,proto3" json:"ready_to_submit,omitempty"`
	// The state of each step in the form
	Steps []*FormStep `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	// RFC 3339 timestamp -- if set, the user has started filling out the form
	Started       string `protobuf:"bytes,4,opt,name=started,proto3" json:"started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormState) Reset() {
	*x = FormState{}
	mi := &file_bff_models_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormState) ProtoMessage() {}

func (x *FormState) ProtoReflect() protoreflect.Message {
	mi := &file_bff_models_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormState.ProtoReflect.Descriptor instead.
func (*FormState) Descriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *FormState) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *FormState) GetReadyToSubmit() bool {
	if x != nil {
		return x.ReadyToSubmit
	}
	return false
}

func (x *FormState) GetSteps() []*FormStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *FormState) GetStarted() string {
	if x != nil {
		return x.Started
	}
	return ""
}

// FormStep contains the state of a single step in an organization's registration form.
type FormStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormStep) Reset() {
	*x = FormStep{}
	mi := &file_bff_models_v1_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormStep) ProtoMessage() {}

func (x *FormStep) ProtoReflect() protoreflect.Message {
	mi := &file_bff_models_v1_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormStep.ProtoReflect.Descriptor instead.
func (*FormStep) Descriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{3}
}

func (x *FormStep) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *FormStep) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FormStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DirectoryRecord contains the information needed to lookup a VASP in a directory service.
type DirectoryRecord struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RegisteredDirectory string                 `protobuf:"bytes,2,opt,name=registered_directory,json=registeredDirectory,proto3" json:"registered_directory,omitempty"`
	CommonName          string                 `protobuf:"bytes,3,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	// RFC 3339 timestamp -- if set, the form has been submitted without error
	Submitted     string `protobuf:"bytes,15,opt,name=submitted,proto3" json:"submitted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryRecord) Reset() {
	*x = DirectoryRecord{}
	mi := &file_bff_models_v1_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryRecord) ProtoMessage() {}

func (x *DirectoryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_bff_models_v1_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryRecord.ProtoReflect.Descriptor instead.
func (*DirectoryRecord) Descriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{4}
}

func (x *DirectoryRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DirectoryRecord) GetRegisteredDirectory() string {
	if x != nil {
		return x.RegisteredDirectory
	}
	return ""
}

func (x *DirectoryRecord) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *DirectoryRecord) GetSubmitted() string {
	if x != nil {
		return x.Submitted
	}
	return ""
}

// RegistrationForm is an extension of the TRISA GDS RegistrationRequest with BFF fields.
type RegistrationForm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Business information: Basic Details Step
	Website          string                   `protobuf:"bytes,1,opt,name=website,proto3" json:"website,omitempty"`
	BusinessCategory v1beta1.BusinessCategory `protobuf:"varint,2,opt,name=business_category,json=businessCategory,proto3,enum=trisa.gds.models.v1beta1.BusinessCategory" json:"business_category,omitempty"`
	VaspCategories   []string                 `protobuf:"bytes,3,rep,name=vasp_categories,json=vaspCategories,proto3" json:"vasp_categories,omitempty"`
	EstablishedOn    string                   `protobuf:"bytes,4,opt,name=established_on,json=establishedOn,proto3" json:"established_on,omitempty"`
	OrganizationName string                   `protobuf:"bytes,5,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	// IVMS 101 Legal Person record: Legal Person Step
	Entity *ivms101.LegalPerson `protobuf:"bytes,11,opt,name=entity,proto3" json:"entity,omitempty"`
	// Directory Record contacts: Contacts Step
	Contacts *v1beta1.Contacts `protobuf:"bytes,12,opt,name=contacts,proto3" json:"contacts,omitempty"`
	// TRIXO Form: TRIXO Step
	Trixo *v1beta1.TRIXOQuestionnaire `protobuf:"bytes,13,opt,name=trixo,proto3" json:"trixo,omitempty"`
	// Network-specific information and submission details: TRISA Step
	Testnet *NetworkDetails `protobuf:"bytes,14,opt,name=testnet,proto3" json:"testnet,omitempty"`
	Mainnet *NetworkDetails `protobuf:"bytes,15,opt,name=mainnet,proto3" json:"mainnet,omitempty"`
	// Current progress of the form for the frontend
	State         *FormState `protobuf:"bytes,20,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationForm) Reset() {
	*x = RegistrationForm{}
	mi := &file_bff_models_v1_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationForm) ProtoMessage() {}

func (x *RegistrationForm) ProtoReflect() protoreflect.Message {
	mi := &file_bff_models_v1_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationForm.ProtoReflect.Descriptor instead.
func (*RegistrationForm) Descriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{5}
}

func (x *RegistrationForm) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *RegistrationForm) GetBusinessCategory() v1beta1.BusinessCategory {
	if x != nil {
		return x.BusinessCategory
	}
	return v1beta1.BusinessCategory(0)
}

func (x *RegistrationForm) GetVaspCategories() []string {
	if x != nil {
		return x.VaspCategories
	}
	return nil
}

func (x *RegistrationForm) GetEstablishedOn() string {
	if x != nil {
		return x.EstablishedOn
	}
	return ""
}

func (x *RegistrationForm) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *RegistrationForm) GetEntity() *ivms101.LegalPerson {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *RegistrationForm) GetContacts() *v1beta1.Contacts {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *RegistrationForm) GetTrixo() *v1beta1.TRIXOQuestionnaire {
	if x != nil {
		return x.Trixo
	}
	return nil
}

func (x *RegistrationForm) GetTestnet() *NetworkDetails {
	if x != nil {
		return x.Testnet
	}
	return nil
}

func (x *RegistrationForm) GetMainnet() *NetworkDetails {
	if x != nil {
		return x.Mainnet
	}
	return nil
}

func (x *RegistrationForm) GetState() *FormState {
	if x != nil {
		return x.State
	}
	return nil
}

// NetworkDetails contains directory-service specific submission information such as the
// certificate request and information about when the registration form was submitted.
type NetworkDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Certificate request information
	CommonName    string   `protobuf:"bytes,1,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	Endpoint      string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	DnsNames      []string `protobuf:"bytes,3,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkDetails) Reset() {
	*x = NetworkDetails{}
	mi := &file_bff_models_v1_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkDetails) ProtoMessage() {}

func (x *NetworkDetails) ProtoReflect() protoreflect.Message {
	mi := &file_bff_models_v1_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkDetails.ProtoReflect.Descriptor instead.
func (*NetworkDetails) Descriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkDetails) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *NetworkDetails) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *NetworkDetails) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

// Announcements are made by network administrators to inform all TRISA members of
// important events, maintenance, or milestones. These are broadcast from the BFF so
// that all members receive the same announcement.
type Announcement struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body     string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	PostDate string                 `protobuf:"bytes,4,opt,name=post_date,json=postDate,proto3" json:"post_date,omitempty"`
	Author   string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	// Metadata as RFC3339Nano Timestamps
	Created       string `protobuf:"bytes,14,opt,name=created,proto3" json:"created,omitempty"`
	Modified      string `protobuf:"bytes,15,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Announcement) Reset() {
	*x = Announcement{}
	mi := &file_bff_models_v1_models_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Announcement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announcement) ProtoMessage() {}

func (x *Announcement) ProtoReflect() protoreflect.Message {
	mi := &file_bff_models_v1_models_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announcement.ProtoReflect.Descriptor instead.
func (*Announcement) Descriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{7}
}

func (x *Announcement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Announcement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Announcement) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Announcement) GetPostDate() string {
	if x != nil {
		return x.PostDate
	}
	return ""
}

func (x *Announcement) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Announcement) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Announcement) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

// Announcements are stored in months to enable fast retrieval of the latest
// announcements in a specific time range without a reversal traversal of time-ordered
// anncouncement objects. Note that the annoucements are stored in a slice instead of
// a map to reduce data storage overhead. Accessing a specific announcement requires
// iterating over the annoucements, but the number of annoucements in a month should not
// be unbounded, so this cost is acceptable for data storage performance.
type AnnouncementMonth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Announcements []*Announcement        `protobuf:"bytes,2,rep,name=announcements,proto3" json:"announcements,omitempty"`
	// Metadata as RFC3339Nano Timestamps
	Created       string `protobuf:"bytes,14,opt,name=created,proto3" json:"created,omitempty"`
	Modified      string `protobuf:"bytes,15,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnouncementMonth) Reset() {
	*x = AnnouncementMonth{}
	mi := &file_bff_models_v1_models_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementMonth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementMonth) ProtoMessage() {}

func (x *AnnouncementMonth) ProtoReflect() protoreflect.Message {
	mi := &file_bff_models_v1_models_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementMonth.ProtoReflect.Descriptor instead.
func (*AnnouncementMonth) Descriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{8}
}

func (x *AnnouncementMonth) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AnnouncementMonth) GetAnnouncements() []*Announcement {
	if x != nil {
		return x.Announcements
	}
	return nil
}

func (x *AnnouncementMonth) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *AnnouncementMonth) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

// ActivityDay represents activity across multiple networks aggregated over a single
// day.
type ActivityDay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The date which the activities occurred on
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// Activity counts broken down by network and activity type
	Activity *ActivityCount `protobuf:"bytes,3,opt,name=activity,proto3" json:"activity,omitempty"`
	// Activity counts broken down by VASP
	VaspActivity  map[string]*ActivityCount `protobuf:"bytes,4,rep,name=vasp_activity,json=vaspActivity,proto3" json:"vasp_activity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityDay) Reset() {
	*x = ActivityDay{}
	mi := &file_bff_models_v1_models_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityDay) ProtoMessage() {}

func (x *ActivityDay) ProtoReflect() protoreflect.Message {
	mi := &file_bff_models_v1_models_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityDay.ProtoReflect.Descriptor instead.
func (*ActivityDay) Descriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{9}
}

func (x *ActivityDay) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ActivityDay) GetActivity() *ActivityCount {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *ActivityDay) GetVaspActivity() map[string]*ActivityCount {
	if x != nil {
		return x.VaspActivity
	}
	return nil
}

// Activity counts are aggregated by day and stored in months to enable
// efficient lookups of multiple days of counts for time series representations.
type ActivityMonth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Date  string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Days  []*ActivityDay         `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	// Metadata as RFC3339Nano Timestamps
	Created       string `protobuf:"bytes,14,opt,name=created,proto3" json:"created,omitempty"`
	Modified      string `protobuf:"bytes,15,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityMonth) Reset() {
	*x = ActivityMonth{}
	mi := &file_bff_models_v1_models_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityMonth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityMonth) ProtoMessage() {}

func (x *ActivityMonth) ProtoReflect() protoreflect.Message {
	mi := &file_bff_models_v1_models_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityMonth.ProtoReflect.Descriptor instead.
func (*ActivityMonth) Descriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{10}
}

func (x *ActivityMonth) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ActivityMonth) GetDays() []*ActivityDay {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *ActivityMonth) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *ActivityMonth) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

// ActivityCount represents counts broken down by activity type and network.
type ActivityCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Testnet       map[string]uint64      `protobuf:"bytes,1,rep,name=testnet,proto3" json:"testnet,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Mainnet       map[string]uint64      `protobuf:"bytes,2,rep,name=mainnet,proto3" json:"mainnet,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RVASP         map[string]uint64      `protobuf:"bytes,3,rep,name=RVASP,proto3" json:"RVASP,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityCount) Reset() {
	*x = ActivityCount{}
	mi := &file_bff_models_v1_models_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityCount) ProtoMessage() {}

func (x *ActivityCount) ProtoReflect() protoreflect.Message {
	mi := &file_bff_models_v1_models_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityCount.ProtoReflect.Descriptor instead.
func (*ActivityCount) Descriptor() ([]byte, []int) {
	return file_bff_models_v1_models_proto_rawDescGZIP(), []int{11}
}

func (x *ActivityCount) GetTestnet() map[string]uint64 {
	if x != nil {
		return x.Testnet
	}
	return nil
}

func (x *ActivityCount) GetMainnet() map[string]uint64 {
	if x != nil {
		return x.Mainnet
	}
	return nil
}

func (x *ActivityCount) GetRVASP() map[string]uint64 {
	if x != nil {
		return x.RVASP
	}
	return nil
}

var File_bff_models_v1_models_proto protoreflect.FileDescriptor

const file_bff_models_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1abff/models/v1/models.proto\x12\rbff.models.v1\x1a\x15ivms101/ivms101.proto\x1a%trisa/gds/models/v1beta1/models.proto\"\xa8\x04\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\blogo_url\x18\x03 \x01(\tR\alogoUrl\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x128\n" +
	"\atestnet\x18\n" +
	" \x01(\v2\x1e.bff.models.v1.DirectoryRecordR\atestnet\x128\n" +
	"\amainnet\x18\v \x01(\v2\x1e.bff.models.v1.DirectoryRecordR\amainnet\x12T\n" +
	"\rcollaborators\x18\f \x03(\v2..bff.models.v1.Organization.CollaboratorsEntryR\rcollaborators\x12C\n" +
	"\fregistration\x18\r \x01(\v2\x1f.bff.models.v1.RegistrationFormR\fregistration\x12\x18\n" +
	"\acreated\x18\x0e \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\x0f \x01(\tR\bmodified\x1a]\n" +
	"\x12CollaboratorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.bff.models.v1.CollaboratorR\x05value:\x028\x01\"\xae\x02\n" +
	"\fCollaborator\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\bR\bverified\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vmodified_at\x18\v \x01(\tR\n" +
	"modifiedAt\x12\x1b\n" +
	"\tjoined_at\x18\f \x01(\tR\bjoinedAt\x12\x1d\n" +
	"\n" +
	"last_login\x18\r \x01(\tR\tlastLogin\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x0e \x01(\tR\texpiresAt\"\x96\x01\n" +
	"\tFormState\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\x05R\acurrent\x12&\n" +
	"\x0fready_to_submit\x18\x02 \x01(\bR\rreadyToSubmit\x12-\n" +
	"\x05steps\x18\x03 \x03(\v2\x17.bff.models.v1.FormStepR\x05steps\x12\x18\n" +
	"\astarted\x18\x04 \x01(\tR\astarted\"H\n" +
	"\bFormStep\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x93\x01\n" +
	"\x0fDirectoryRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x14registered_directory\x18\x02 \x01(\tR\x13registeredDirectory\x12\x1f\n" +
	"\vcommon_name\x18\x03 \x01(\tR\n" +
	"commonName\x12\x1c\n" +
	"\tsubmitted\x18\x0f \x01(\tR\tsubmitted\"\xd6\x04\n" +
	"\x10RegistrationForm\x12\x18\n" +
	"\awebsite\x18\x01 \x01(\tR\awebsite\x12W\n" +
	"\x11business_category\x18\x02 \x01(\x0e2*.trisa.gds.models.v1beta1.BusinessCategoryR\x10businessCategory\x12'\n" +
	"\x0fvasp_categories\x18\x03 \x03(\tR\x0evaspCategories\x12%\n" +
	"\x0eestablished_on\x18\x04 \x01(\tR\restablishedOn\x12+\n" +
	"\x11organization_name\x18\x05 \x01(\tR\x10organizationName\x12,\n" +
	"\x06entity\x18\v \x01(\v2\x14.ivms101.LegalPersonR\x06entity\x12>\n" +
	"\bcontacts\x18\f \x01(\v2\".trisa.gds.models.v1beta1.ContactsR\bcontacts\x12B\n" +
	"\x05trixo\x18\r \x01(\v2,.trisa.gds.models.v1beta1.TRIXOQuestionnaireR\x05trixo\x127\n" +
	"\atestnet\x18\x0e \x01(\v2\x1d.bff.models.v1.NetworkDetailsR\atestnet\x127\n" +
	"\amainnet\x18\x0f \x01(\v2\x1d.bff.models.v1.NetworkDetailsR\amainnet\x12.\n" +
	"\x05state\x18\x14 \x01(\v2\x18.bff.models.v1.FormStateR\x05state\"j\n" +
	"\x0eNetworkDetails\x12\x1f\n" +
	"\vcommon_name\x18\x01 \x01(\tR\n" +
	"commonName\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1b\n" +
	"\tdns_names\x18\x03 \x03(\tR\bdnsNames\"\xb3\x01\n" +
	"\fAnnouncement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1b\n" +
	"\tpost_date\x18\x04 \x01(\tR\bpostDate\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x18\n" +
	"\acreated\x18\x0e \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\x0f \x01(\tR\bmodified\"\xa0\x01\n" +
	"\x11AnnouncementMonth\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12A\n" +
	"\rannouncements\x18\x02 \x03(\v2\x1b.bff.models.v1.AnnouncementR\rannouncements\x12\x18\n" +
	"\acreated\x18\x0e \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\x0f \x01(\tR\bmodified\"\x8d\x02\n" +
	"\vActivityDay\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x128\n" +
	"\bactivity\x18\x03 \x01(\v2\x1c.bff.models.v1.ActivityCountR\bactivity\x12Q\n" +
	"\rvasp_activity\x18\x04 \x03(\v2,.bff.models.v1.ActivityDay.VaspActivityEntryR\fvaspActivity\x1a]\n" +
	"\x11VaspActivityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.bff.models.v1.ActivityCountR\x05value:\x028\x01\"\x89\x01\n" +
	"\rActivityMonth\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12.\n" +
	"\x04days\x18\x02 \x03(\v2\x1a.bff.models.v1.ActivityDayR\x04days\x12\x18\n" +
	"\acreated\x18\x0e \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\x0f \x01(\tR\bmodified\"\x8a\x03\n" +
	"\rActivityCount\x12C\n" +
	"\atestnet\x18\x01 \x03(\v2).bff.models.v1.ActivityCount.TestnetEntryR\atestnet\x12C\n" +
	"\amainnet\x18\x02 \x03(\v2).bff.models.v1.ActivityCount.MainnetEntryR\amainnet\x12=\n" +
	"\x05RVASP\x18\x03 \x03(\v2'.bff.models.v1.ActivityCount.RVASPEntryR\x05RVASP\x1a:\n" +
	"\fTestnetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a:\n" +
	"\fMainnetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"RVASPEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01*B\n" +
	"\x11AttentionSeverity\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ALERT\x10\x03*\xba\x01\n" +
	"\x0fAttentionAction\x12\r\n" +
	"\tNO_ACTION\x10\x00\x12\x16\n" +
	"\x12START_REGISTRATION\x10\x01\x12\x19\n" +
	"\x15COMPLETE_REGISTRATION\x10\x02\x12\x12\n" +
	"\x0eSUBMIT_TESTNET\x10\x03\x12\x12\n" +
	"\x0eSUBMIT_MAINNET\x10\x04\x12\x11\n" +
	"\rVERIFY_EMAILS\x10\x05\x12\x15\n" +
	"\x11RENEW_CERTIFICATE\x10\x06\x12\x13\n" +
	"\x0fCONTACT_SUPPORT\x10\aB;Z9github.com/trisacrypto/directory/pkg/bff/models/v1;modelsb\x06proto3"

var (
	file_bff_models_v1_models_proto_rawDescOnce sync.Once
	file_bff_models_v1_models_proto_rawDescData []byte
)

func file_bff_models_v1_models_proto_rawDescGZIP() []byte {
	file_bff_models_v1_models_proto_rawDescOnce.Do(func() {
		file_bff_models_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bff_models_v1_models_proto_rawDesc), len(file_bff_models_v1_models_proto_rawDesc)))
	})
	return file_bff_models_v1_models_proto_rawDescData
}

var file_bff_models_v1_models_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bff_models_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_bff_models_v1_models_proto_goTypes = []any{
	(AttentionSeverity)(0),             // 0: bff.models.v1.AttentionSeverity
	(AttentionAction)(0),               // 1: bff.models.v1.AttentionAction
	(*Organization)(nil),               // 2: bff.models.v1.Organization
	(*Collaborator)(nil),               // 3: bff.models.v1.Collaborator
	(*FormState)(nil),                  // 4: bff.models.v1.FormState
	(*FormStep)(nil),                   // 5: bff.models.v1.FormStep
	(*DirectoryRecord)(nil),            // 6: bff.models.v1.DirectoryRecord
	(*RegistrationForm)(nil),           // 7: bff.models.v1.RegistrationForm
	(*NetworkDetails)(nil),             // 8: bff.models.v1.NetworkDetails
	(*Announcement)(nil),               // 9: bff.models.v1.Announcement
	(*AnnouncementMonth)(nil),          // 10: bff.models.v1.AnnouncementMonth
	(*ActivityDay)(nil),                // 11: bff.models.v1.ActivityDay
	(*ActivityMonth)(nil),              // 12: bff.models.v1.ActivityMonth
	(*ActivityCount)(nil),              // 13: bff.models.v1.ActivityCount
	nil,                                // 14: bff.models.v1.Organization.CollaboratorsEntry
	nil,                                // 15: bff.models.v1.ActivityDay.VaspActivityEntry
	nil,                                // 16: bff.models.v1.ActivityCount.TestnetEntry
	nil,                                // 17: bff.models.v1.ActivityCount.MainnetEntry
	nil,                                // 18: bff.models.v1.ActivityCount.RVASPEntry
	(v1beta1.BusinessCategory)(0),      // 19: trisa.gds.models.v1beta1.BusinessCategory
	(*ivms101.LegalPerson)(nil),        // 20: ivms101.LegalPerson
	(*v1beta1.Contacts)(nil),           // 21: trisa.gds.models.v1beta1.Contacts
	(*v1beta1.TRIXOQuestionnaire)(nil), // 22: trisa.gds.models.v1beta1.TRIXOQuestionnaire
}
var file_bff_models_v1_models_proto_depIdxs = []int32{
	6,  // 0: bff.models.v1.Organization.testnet:type_name -> bff.models.v1.DirectoryRecord
	6,  // 1: bff.models.v1.Organization.mainnet:type_name -> bff.models.v1.DirectoryRecord
	14, // 2: bff.models.v1.Organization.collaborators:type_name -> bff.models.v1.Organization.CollaboratorsEntry
	7,  // 3: bff.models.v1.Organization.registration:type_name -> bff.models.v1.RegistrationForm
	5,  // 4: bff.models.v1.FormState.steps:type_name -> bff.models.v1.FormStep
	19, // 5: bff.models.v1.RegistrationForm.business_category:type_name -> trisa.gds.models.v1beta1.BusinessCategory
	20, // 6: bff.models.v1.RegistrationForm.entity:type_name -> ivms101.LegalPerson
	21, // 7: bff.models.v1.RegistrationForm.contacts:type_name -> trisa.gds.models.v1beta1.Contacts
	22, // 8: bff.models.v1.RegistrationForm.trixo:type_name -> trisa.gds.models.v1beta1.TRIXOQuestionnaire
	8,  // 9: bff.models.v1.RegistrationForm.testnet:type_name -> bff.models.v1.NetworkDetails
	8,  // 10: bff.models.v1.RegistrationForm.mainnet:type_name -> bff.models.v1.NetworkDetails
	4,  // 11: bff.models.v1.RegistrationForm.state:type_name -> bff.models.v1.FormState
	9,  // 12: bff.models.v1.AnnouncementMonth.announcements:type_name -> bff.models.v1.Announcement
	13, // 13: bff.models.v1.ActivityDay.activity:type_name -> bff.models.v1.ActivityCount
	15, // 14: bff.models.v1.ActivityDay.vasp_activity:type_name -> bff.models.v1.ActivityDay.VaspActivityEntry
	11, // 15: bff.models.v1.ActivityMonth.days:type_name -> bff.models.v1.ActivityDay
	16, // 16: bff.models.v1.ActivityCount.testnet:type_name -> bff.models.v1.ActivityCount.TestnetEntry
	17, // 17: bff.models.v1.ActivityCount.mainnet:type_name -> bff.models.v1.ActivityCount.MainnetEntry
	18, // 18: bff.models.v1.ActivityCount.RVASP:type_name -> bff.models.v1.ActivityCount.RVASPEntry
	3,  // 19: bff.models.v1.Organization.CollaboratorsEntry.value:type_name -> bff.models.v1.Collaborator
	13, // 20: bff.models.v1.ActivityDay.VaspActivityEntry.value:type_name -> bff.models.v1.ActivityCount
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_bff_models_v1_models_proto_init() }
func file_bff_models_v1_models_proto_init() {
	if File_bff_models_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bff_models_v1_models_proto_rawDesc), len(file_bff_models_v1_models_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bff_models_v1_models_proto_goTypes,
		DependencyIndexes: file_bff_models_v1_models_proto_depIdxs,
		EnumInfos:         file_bff_models_v1_models_proto_enumTypes,
		MessageInfos:      file_bff_models_v1_models_proto_msgTypes,
	}.Build()
	File_bff_models_v1_models_proto = out.File
	file_bff_models_v1_models_proto_goTypes = nil
	file_bff_models_v1_models_proto_depIdxs = nil
}
