{
 "title": "Trtl Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total RPCs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "trtl_deletes" },
    { "expr": "trtl_puts" },
    { "expr": "trtl_gets" },
    { "expr": "trtl_iters" },
    { "expr": "trtl_cursors" }
   ]
  },
  {
   "title": "RPCs/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(trtl_deletes{}[$__interval])"
    },
    { "expr": "rate(trtl_gets{}[$__interval])" },
    { "expr": "rate(trtl_puts{}[$__interval])" },
    {
     "expr": "rate(trtl_iters{}[$__interval])"
    },
    {
     "expr": "rate(trtl_cursors{}[$__interval])"
    }
   ]
  },
  {
   "title": "Get Statistics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(trtl_latency_sum{call=\"Get\"}[$__interval]) / rate(trtl_latency_count{call=\"Get\"}[$__interval])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(.50, rate(trtl_latency_bucket{call=\"Get\"}[$__interval]))",
     "legendFormat": "Median Latency"
    },
    {
     "expr": "histogram_quantile(.75, rate(trtl_latency_bucket{call=\"Get\"}[$__interval]))",
     "legendFormat": "Third Quartile Latency"
    }
   ]
  },
  {
   "title": "Get Latency Distribution",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trtl_latency_bucket{call=\"Get\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RPC Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(trtl_latency_bucket{}[$__interval])) by (le)",
     "legendFormat": "{{le}} ms"
    }
   ]
  },
  {
   "title": "Put Statistics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(trtl_latency_sum{call=\"Put\"}[$__interval]) / rate(trtl_latency_count{call=\"Put\"}[$__interval])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(.50, rate(trtl_latency_bucket{call=\"Put\"}[$__interval]))",
     "legendFormat": "Median Latency"
    },
    {
     "expr": "histogram_quantile(.75, rate(trtl_latency_bucket{call=\"Put\"}[$__interval]))",
     "legendFormat": "Third Quartile Latency"
    }
   ]
  },
  {
   "title": "Put Latency Distribution",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trtl_latency_bucket{call=\"Put\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Delete Statistics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(trtl_latency_sum{call=\"Delete\"}[$__interval]) / rate(trtl_latency_count{call=\"Delete\"}[$__interval])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(.50, rate(trtl_latency_bucket{call=\"Delete\"}[$__interval]))",
     "legendFormat": "Median Latency"
    },
    {
     "expr": "histogram_quantile(.75, rate(trtl_latency_bucket{call=\"Delete\"}[$__interval]))",
     "legendFormat": "Third Quartile Latency"
    }
   ]
  },
  {
   "title": "Delete Latency Distribution",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trtl_latency_bucket{call=\"Delete\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Iter Statistics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(trtl_latency_sum{call=\"Iter\"}[$__interval]) / rate(trtl_latency_count{call=\"Iter\"}[$__interval])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(.50, rate(trtl_latency_bucket{call=\"Iter\"}[$__interval]))",
     "legendFormat": "Median Latency"
    },
    {
     "expr": "histogram_quantile(.75, rate(trtl_latency_bucket{call=\"Iter\"}[$__interval]))",
     "legendFormat": "Third Quartile Latency"
    }
   ]
  },
  {
   "title": "Iter Latency Distribution",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trtl_latency_bucket{call=\"Iter\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Cursor Statistics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(trtl_latency_sum{call=\"Cursor\"}[$__interval]) / rate(trtl_latency_count{call=\"Cursor\"}[$__interval])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(.50, rate(trtl_latency_bucket{call=\"Cursor\"}[$__interval]))",
     "legendFormat": "Median Latency"
    },
    {
     "expr": "histogram_quantile(.75, rate(trtl_latency_bucket{call=\"Cursor\"}[$__interval]))",
     "legendFormat": "Third Quartile Latency"
    }
   ]
  },
  {
   "title": "Cursor Latency Distribution",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trtl_latency_bucket{call=\"Cursor\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}