// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: gds/members/v1alpha1/members.proto

package members

import (
	ivms101 "github.com/trisacrypto/trisa/pkg/ivms101"
	v1beta1 "github.com/trisacrypto/trisa/pkg/trisa/gds/models/v1beta1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListRequest manages paginating the VASP listing. If there are more results than the
// specified page size, then the ListReply will return a page token; that token can be
// used to fetch the next page so long as the parameters of the original request are not
// modified (e.g. any filters or pagination parameters).
// See https://cloud.google.com/apis/design/design_patterns#list_pagination for more.
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // specify the number of results per page, cannot change between page requests (default 100)
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // specify the page token to fetch the next page of results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_gds_members_v1alpha1_members_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListReply returns an abbreviated listing of VASP details intended to facilitate p2p
// key exchanges or more detailed lookups against the Directory Service.
type ListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vasps         []*VASPMember          `protobuf:"bytes,1,rep,name=vasps,proto3" json:"vasps,omitempty"`                                        // a list of VASP information for the requested page
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // if specified, another page of results exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_gds_members_v1alpha1_members_proto_rawDescGZIP(), []int{1}
}

func (x *ListReply) GetVasps() []*VASPMember {
	if x != nil {
		return x.Vasps
	}
	return nil
}

func (x *ListReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// VASPMember is a lightweight data structure containing enough information to
// facilitate p2p exchanges or more detailed lookups against the Directory Service.
// Note: This should not contain any sensitive VASP information since it is returned on
// the publicly accessible List and Summary APIs.
type VASPMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The uniquely identifying components of the VASP in the directory service
	Id                  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RegisteredDirectory string `protobuf:"bytes,2,opt,name=registered_directory,json=registeredDirectory,proto3" json:"registered_directory,omitempty"`
	CommonName          string `protobuf:"bytes,3,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	// Address to connect to the remote VASP on to perform a TRISA request
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Extra details used to facilitate searches and matching
	Name             string                    `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Website          string                    `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	Country          string                    `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	BusinessCategory v1beta1.BusinessCategory  `protobuf:"varint,8,opt,name=business_category,json=businessCategory,proto3,enum=trisa.gds.models.v1beta1.BusinessCategory" json:"business_category,omitempty"`
	VaspCategories   []string                  `protobuf:"bytes,9,rep,name=vasp_categories,json=vaspCategories,proto3" json:"vasp_categories,omitempty"`
	VerifiedOn       string                    `protobuf:"bytes,10,opt,name=verified_on,json=verifiedOn,proto3" json:"verified_on,omitempty"`
	Status           v1beta1.VerificationState `protobuf:"varint,11,opt,name=status,proto3,enum=trisa.gds.models.v1beta1.VerificationState" json:"status,omitempty"`
	FirstListed      string                    `protobuf:"bytes,12,opt,name=first_listed,json=firstListed,proto3" json:"first_listed,omitempty"`
	LastUpdated      string                    `protobuf:"bytes,13,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VASPMember) Reset() {
	*x = VASPMember{}
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VASPMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VASPMember) ProtoMessage() {}

func (x *VASPMember) ProtoReflect() protoreflect.Message {
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VASPMember.ProtoReflect.Descriptor instead.
func (*VASPMember) Descriptor() ([]byte, []int) {
	return file_gds_members_v1alpha1_members_proto_rawDescGZIP(), []int{2}
}

func (x *VASPMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VASPMember) GetRegisteredDirectory() string {
	if x != nil {
		return x.RegisteredDirectory
	}
	return ""
}

func (x *VASPMember) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *VASPMember) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *VASPMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VASPMember) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *VASPMember) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *VASPMember) GetBusinessCategory() v1beta1.BusinessCategory {
	if x != nil {
		return x.BusinessCategory
	}
	return v1beta1.BusinessCategory(0)
}

func (x *VASPMember) GetVaspCategories() []string {
	if x != nil {
		return x.VaspCategories
	}
	return nil
}

func (x *VASPMember) GetVerifiedOn() string {
	if x != nil {
		return x.VerifiedOn
	}
	return ""
}

func (x *VASPMember) GetStatus() v1beta1.VerificationState {
	if x != nil {
		return x.Status
	}
	return v1beta1.VerificationState(0)
}

func (x *VASPMember) GetFirstListed() string {
	if x != nil {
		return x.FirstListed
	}
	return ""
}

func (x *VASPMember) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

// SummaryRequest allows the caller to specify parameters for the returned summary.
type SummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The start date for determining how many members are new - optional
	Since string `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	// Include your VASP ID to return details about your VASP record in the summary - optional
	MemberId      string `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_gds_members_v1alpha1_members_proto_rawDescGZIP(), []int{3}
}

func (x *SummaryRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *SummaryRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

// SummaryReply returns summary info about the members in the Directory Service.
type SummaryReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Counts of VASPs and certificates
	Vasps              int32 `protobuf:"varint,1,opt,name=vasps,proto3" json:"vasps,omitempty"`
	CertificatesIssued int32 `protobuf:"varint,2,opt,name=certificates_issued,json=certificatesIssued,proto3" json:"certificates_issued,omitempty"`
	NewMembers         int32 `protobuf:"varint,3,opt,name=new_members,json=newMembers,proto3" json:"new_members,omitempty"`
	// Details for the requested VASP
	MemberInfo    *VASPMember `protobuf:"bytes,4,opt,name=member_info,json=memberInfo,proto3" json:"member_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryReply) Reset() {
	*x = SummaryReply{}
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryReply) ProtoMessage() {}

func (x *SummaryReply) ProtoReflect() protoreflect.Message {
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryReply.ProtoReflect.Descriptor instead.
func (*SummaryReply) Descriptor() ([]byte, []int) {
	return file_gds_members_v1alpha1_members_proto_rawDescGZIP(), []int{4}
}

func (x *SummaryReply) GetVasps() int32 {
	if x != nil {
		return x.Vasps
	}
	return 0
}

func (x *SummaryReply) GetCertificatesIssued() int32 {
	if x != nil {
		return x.CertificatesIssued
	}
	return 0
}

func (x *SummaryReply) GetNewMembers() int32 {
	if x != nil {
		return x.NewMembers
	}
	return 0
}

func (x *SummaryReply) GetMemberInfo() *VASPMember {
	if x != nil {
		return x.MemberInfo
	}
	return nil
}

// DetailsRequest allows the caller to specify the VASP member to retrieve details for.
type DetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailsRequest) Reset() {
	*x = DetailsRequest{}
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailsRequest) ProtoMessage() {}

func (x *DetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailsRequest.ProtoReflect.Descriptor instead.
func (*DetailsRequest) Descriptor() ([]byte, []int) {
	return file_gds_members_v1alpha1_members_proto_rawDescGZIP(), []int{5}
}

func (x *DetailsRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

// MemberDetails returns details about the requested VASP member.
type MemberDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Summary information about the VASP member
	MemberSummary *VASPMember `protobuf:"bytes,1,opt,name=member_summary,json=memberSummary,proto3" json:"member_summary,omitempty"`
	// The IVMS101 legal person identifying the VASP member
	LegalPerson *ivms101.LegalPerson `protobuf:"bytes,2,opt,name=legal_person,json=legalPerson,proto3" json:"legal_person,omitempty"`
	// The TRIXO questionnaire used to register the VASP
	Trixo *v1beta1.TRIXOQuestionnaire `protobuf:"bytes,3,opt,name=trixo,proto3" json:"trixo,omitempty"`
	// The Contacts for a registered VASP
	Contacts      *v1beta1.Contacts `protobuf:"bytes,4,opt,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberDetails) Reset() {
	*x = MemberDetails{}
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberDetails) ProtoMessage() {}

func (x *MemberDetails) ProtoReflect() protoreflect.Message {
	mi := &file_gds_members_v1alpha1_members_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberDetails.ProtoReflect.Descriptor instead.
func (*MemberDetails) Descriptor() ([]byte, []int) {
	return file_gds_members_v1alpha1_members_proto_rawDescGZIP(), []int{6}
}

func (x *MemberDetails) GetMemberSummary() *VASPMember {
	if x != nil {
		return x.MemberSummary
	}
	return nil
}

func (x *MemberDetails) GetLegalPerson() *ivms101.LegalPerson {
	if x != nil {
		return x.LegalPerson
	}
	return nil
}

func (x *MemberDetails) GetTrixo() *v1beta1.TRIXOQuestionnaire {
	if x != nil {
		return x.Trixo
	}
	return nil
}

func (x *MemberDetails) GetContacts() *v1beta1.Contacts {
	if x != nil {
		return x.Contacts
	}
	return nil
}

var File_gds_members_v1alpha1_members_proto protoreflect.FileDescriptor

const file_gds_members_v1alpha1_members_proto_rawDesc = "" +
	"\n" +
	"\"gds/members/v1alpha1/members.proto\x12\x14gds.members.v1alpha1\x1a%trisa/gds/models/v1beta1/models.proto\x1a\x15ivms101/ivms101.proto\"I\n" +
	"\vListRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"k\n" +
	"\tListReply\x126\n" +
	"\x05vasps\x18\x01 \x03(\v2 .gds.members.v1alpha1.VASPMemberR\x05vasps\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x82\x04\n" +
	"\n" +
	"VASPMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x14registered_directory\x18\x02 \x01(\tR\x13registeredDirectory\x12\x1f\n" +
	"\vcommon_name\x18\x03 \x01(\tR\n" +
	"commonName\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x18\n" +
	"\awebsite\x18\x06 \x01(\tR\awebsite\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12W\n" +
	"\x11business_category\x18\b \x01(\x0e2*.trisa.gds.models.v1beta1.BusinessCategoryR\x10businessCategory\x12'\n" +
	"\x0fvasp_categories\x18\t \x03(\tR\x0evaspCategories\x12\x1f\n" +
	"\vverified_on\x18\n" +
	" \x01(\tR\n" +
	"verifiedOn\x12C\n" +
	"\x06status\x18\v \x01(\x0e2+.trisa.gds.models.v1beta1.VerificationStateR\x06status\x12!\n" +
	"\ffirst_listed\x18\f \x01(\tR\vfirstListed\x12!\n" +
	"\flast_updated\x18\r \x01(\tR\vlastUpdated\"C\n" +
	"\x0eSummaryRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\tR\x05since\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\"\xb9\x01\n" +
	"\fSummaryReply\x12\x14\n" +
	"\x05vasps\x18\x01 \x01(\x05R\x05vasps\x12/\n" +
	"\x13certificates_issued\x18\x02 \x01(\x05R\x12certificatesIssued\x12\x1f\n" +
	"\vnew_members\x18\x03 \x01(\x05R\n" +
	"newMembers\x12A\n" +
	"\vmember_info\x18\x04 \x01(\v2 .gds.members.v1alpha1.VASPMemberR\n" +
	"memberInfo\"-\n" +
	"\x0eDetailsRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"\x95\x02\n" +
	"\rMemberDetails\x12G\n" +
	"\x0emember_summary\x18\x01 \x01(\v2 .gds.members.v1alpha1.VASPMemberR\rmemberSummary\x127\n" +
	"\flegal_person\x18\x02 \x01(\v2\x14.ivms101.LegalPersonR\vlegalPerson\x12B\n" +
	"\x05trixo\x18\x03 \x01(\v2,.trisa.gds.models.v1beta1.TRIXOQuestionnaireR\x05trixo\x12>\n" +
	"\bcontacts\x18\x04 \x01(\v2\".trisa.gds.models.v1beta1.ContactsR\bcontacts2\x8b\x02\n" +
	"\fTRISAMembers\x12L\n" +
	"\x04List\x12!.gds.members.v1alpha1.ListRequest\x1a\x1f.gds.members.v1alpha1.ListReply\"\x00\x12U\n" +
	"\aSummary\x12$.gds.members.v1alpha1.SummaryRequest\x1a\".gds.members.v1alpha1.SummaryReply\"\x00\x12V\n" +
	"\aDetails\x12$.gds.members.v1alpha1.DetailsRequest\x1a#.gds.members.v1alpha1.MemberDetails\"\x00BCZAgithub.com/trisacrypto/directory/pkg/gds/members/v1alpha1;membersb\x06proto3"

var (
	file_gds_members_v1alpha1_members_proto_rawDescOnce sync.Once
	file_gds_members_v1alpha1_members_proto_rawDescData []byte
)

func file_gds_members_v1alpha1_members_proto_rawDescGZIP() []byte {
	file_gds_members_v1alpha1_members_proto_rawDescOnce.Do(func() {
		file_gds_members_v1alpha1_members_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gds_members_v1alpha1_members_proto_rawDesc), len(file_gds_members_v1alpha1_members_proto_rawDesc)))
	})
	return file_gds_members_v1alpha1_members_proto_rawDescData
}

var file_gds_members_v1alpha1_members_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gds_members_v1alpha1_members_proto_goTypes = []any{
	(*ListRequest)(nil),                // 0: gds.members.v1alpha1.ListRequest
	(*ListReply)(nil),                  // 1: gds.members.v1alpha1.ListReply
	(*VASPMember)(nil),                 // 2: gds.members.v1alpha1.VASPMember
	(*SummaryRequest)(nil),             // 3: gds.members.v1alpha1.SummaryRequest
	(*SummaryReply)(nil),               // 4: gds.members.v1alpha1.SummaryReply
	(*DetailsRequest)(nil),             // 5: gds.members.v1alpha1.DetailsRequest
	(*MemberDetails)(nil),              // 6: gds.members.v1alpha1.MemberDetails
	(v1beta1.BusinessCategory)(0),      // 7: trisa.gds.models.v1beta1.BusinessCategory
	(v1beta1.VerificationState)(0),     // 8: trisa.gds.models.v1beta1.VerificationState
	(*ivms101.LegalPerson)(nil),        // 9: ivms101.LegalPerson
	(*v1beta1.TRIXOQuestionnaire)(nil), // 10: trisa.gds.models.v1beta1.TRIXOQuestionnaire
	(*v1beta1.Contacts)(nil),           // 11: trisa.gds.models.v1beta1.Contacts
}
var file_gds_members_v1alpha1_members_proto_depIdxs = []int32{
	2,  // 0: gds.members.v1alpha1.ListReply.vasps:type_name -> gds.members.v1alpha1.VASPMember
	7,  // 1: gds.members.v1alpha1.VASPMember.business_category:type_name -> trisa.gds.models.v1beta1.BusinessCategory
	8,  // 2: gds.members.v1alpha1.VASPMember.status:type_name -> trisa.gds.models.v1beta1.VerificationState
	2,  // 3: gds.members.v1alpha1.SummaryReply.member_info:type_name -> gds.members.v1alpha1.VASPMember
	2,  // 4: gds.members.v1alpha1.MemberDetails.member_summary:type_name -> gds.members.v1alpha1.VASPMember
	9,  // 5: gds.members.v1alpha1.MemberDetails.legal_person:type_name -> ivms101.LegalPerson
	10, // 6: gds.members.v1alpha1.MemberDetails.trixo:type_name -> trisa.gds.models.v1beta1.TRIXOQuestionnaire
	11, // 7: gds.members.v1alpha1.MemberDetails.contacts:type_name -> trisa.gds.models.v1beta1.Contacts
	0,  // 8: gds.members.v1alpha1.TRISAMembers.List:input_type -> gds.members.v1alpha1.ListRequest
	3,  // 9: gds.members.v1alpha1.TRISAMembers.Summary:input_type -> gds.members.v1alpha1.SummaryRequest
	5,  // 10: gds.members.v1alpha1.TRISAMembers.Details:input_type -> gds.members.v1alpha1.DetailsRequest
	1,  // 11: gds.members.v1alpha1.TRISAMembers.List:output_type -> gds.members.v1alpha1.ListReply
	4,  // 12: gds.members.v1alpha1.TRISAMembers.Summary:output_type -> gds.members.v1alpha1.SummaryReply
	6,  // 13: gds.members.v1alpha1.TRISAMembers.Details:output_type -> gds.members.v1alpha1.MemberDetails
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_gds_members_v1alpha1_members_proto_init() }
func file_gds_members_v1alpha1_members_proto_init() {
	if File_gds_members_v1alpha1_members_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gds_members_v1alpha1_members_proto_rawDesc), len(file_gds_members_v1alpha1_members_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gds_members_v1alpha1_members_proto_goTypes,
		DependencyIndexes: file_gds_members_v1alpha1_members_proto_depIdxs,
		MessageInfos:      file_gds_members_v1alpha1_members_proto_msgTypes,
	}.Build()
	File_gds_members_v1alpha1_members_proto = out.File
	file_gds_members_v1alpha1_members_proto_goTypes = nil
	file_gds_members_v1alpha1_members_proto_depIdxs = nil
}
