// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: gds/admin/v1/admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DirectoryAdministration_Review_FullMethodName = "/gds.admin.v1.DirectoryAdministration/Review"
	DirectoryAdministration_Resend_FullMethodName = "/gds.admin.v1.DirectoryAdministration/Resend"
	DirectoryAdministration_Status_FullMethodName = "/gds.admin.v1.DirectoryAdministration/Status"
)

// DirectoryAdministrationClient is the client API for DirectoryAdministration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// An administrative service that is implemented side-by-side with most directory
// services to review registration requests and perform remote certificate management.
// Because this endpoint necessarily must be authenticated, it is deliberately
// lightweight for the MVP implementation.
type DirectoryAdministrationClient interface {
	Review(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*ReviewReply, error)
	Resend(ctx context.Context, in *ResendRequest, opts ...grpc.CallOption) (*ResendReply, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
}

type directoryAdministrationClient struct {
	cc grpc.ClientConnInterface
}

func NewDirectoryAdministrationClient(cc grpc.ClientConnInterface) DirectoryAdministrationClient {
	return &directoryAdministrationClient{cc}
}

func (c *directoryAdministrationClient) Review(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*ReviewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewReply)
	err := c.cc.Invoke(ctx, DirectoryAdministration_Review_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryAdministrationClient) Resend(ctx context.Context, in *ResendRequest, opts ...grpc.CallOption) (*ResendReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResendReply)
	err := c.cc.Invoke(ctx, DirectoryAdministration_Resend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directoryAdministrationClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, DirectoryAdministration_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectoryAdministrationServer is the server API for DirectoryAdministration service.
// All implementations must embed UnimplementedDirectoryAdministrationServer
// for forward compatibility.
//
// An administrative service that is implemented side-by-side with most directory
// services to review registration requests and perform remote certificate management.
// Because this endpoint necessarily must be authenticated, it is deliberately
// lightweight for the MVP implementation.
type DirectoryAdministrationServer interface {
	Review(context.Context, *ReviewRequest) (*ReviewReply, error)
	Resend(context.Context, *ResendRequest) (*ResendReply, error)
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	mustEmbedUnimplementedDirectoryAdministrationServer()
}

// UnimplementedDirectoryAdministrationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDirectoryAdministrationServer struct{}

func (UnimplementedDirectoryAdministrationServer) Review(context.Context, *ReviewRequest) (*ReviewReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Review not implemented")
}
func (UnimplementedDirectoryAdministrationServer) Resend(context.Context, *ResendRequest) (*ResendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resend not implemented")
}
func (UnimplementedDirectoryAdministrationServer) Status(context.Context, *StatusRequest) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDirectoryAdministrationServer) mustEmbedUnimplementedDirectoryAdministrationServer() {
}
func (UnimplementedDirectoryAdministrationServer) testEmbeddedByValue() {}

// UnsafeDirectoryAdministrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirectoryAdministrationServer will
// result in compilation errors.
type UnsafeDirectoryAdministrationServer interface {
	mustEmbedUnimplementedDirectoryAdministrationServer()
}

func RegisterDirectoryAdministrationServer(s grpc.ServiceRegistrar, srv DirectoryAdministrationServer) {
	// If the following call pancis, it indicates UnimplementedDirectoryAdministrationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DirectoryAdministration_ServiceDesc, srv)
}

func _DirectoryAdministration_Review_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryAdministrationServer).Review(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectoryAdministration_Review_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryAdministrationServer).Review(ctx, req.(*ReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryAdministration_Resend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryAdministrationServer).Resend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectoryAdministration_Resend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryAdministrationServer).Resend(ctx, req.(*ResendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DirectoryAdministration_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryAdministrationServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectoryAdministration_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryAdministrationServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DirectoryAdministration_ServiceDesc is the grpc.ServiceDesc for DirectoryAdministration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DirectoryAdministration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gds.admin.v1.DirectoryAdministration",
	HandlerType: (*DirectoryAdministrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Review",
			Handler:    _DirectoryAdministration_Review_Handler,
		},
		{
			MethodName: "Resend",
			Handler:    _DirectoryAdministration_Resend_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _DirectoryAdministration_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gds/admin/v1/admin.proto",
}
