// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: gds/admin/v1/admin.proto

package admin

import (
	v1beta1 "github.com/trisacrypto/trisa/pkg/trisa/gds/api/v1beta1"
	v1beta11 "github.com/trisacrypto/trisa/pkg/trisa/gds/models/v1beta1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResendRequest_ResendType int32

const (
	ResendRequest_UNKNOWN        ResendRequest_ResendType = 0
	ResendRequest_VERIFY_CONTACT ResendRequest_ResendType = 1
	ResendRequest_REVIEW         ResendRequest_ResendType = 2
	ResendRequest_DELIVER_CERTS  ResendRequest_ResendType = 3
	ResendRequest_REJECTION      ResendRequest_ResendType = 4
)

// Enum value maps for ResendRequest_ResendType.
var (
	ResendRequest_ResendType_name = map[int32]string{
		0: "UNKNOWN",
		1: "VERIFY_CONTACT",
		2: "REVIEW",
		3: "DELIVER_CERTS",
		4: "REJECTION",
	}
	ResendRequest_ResendType_value = map[string]int32{
		"UNKNOWN":        0,
		"VERIFY_CONTACT": 1,
		"REVIEW":         2,
		"DELIVER_CERTS":  3,
		"REJECTION":      4,
	}
)

func (x ResendRequest_ResendType) Enum() *ResendRequest_ResendType {
	p := new(ResendRequest_ResendType)
	*p = x
	return p
}

func (x ResendRequest_ResendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResendRequest_ResendType) Descriptor() protoreflect.EnumDescriptor {
	return file_gds_admin_v1_admin_proto_enumTypes[0].Descriptor()
}

func (ResendRequest_ResendType) Type() protoreflect.EnumType {
	return &file_gds_admin_v1_admin_proto_enumTypes[0]
}

func (x ResendRequest_ResendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResendRequest_ResendType.Descriptor instead.
func (ResendRequest_ResendType) EnumDescriptor() ([]byte, []int) {
	return file_gds_admin_v1_admin_proto_rawDescGZIP(), []int{2, 0}
}

// Registration review requests are sent via email to the TRISA admin email address with
// a lightweight token for review. This endpoint allows administrators to submit a review
// determination back to the directory server.
type ReviewRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the VASP to perform the review for.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The verification token sent in the review email.
	// This token provides lightweight authentication but should be replaced with a more
	// robust authentication and authorization scheme.
	AdminVerificationToken string `protobuf:"bytes,2,opt,name=admin_verification_token,json=adminVerificationToken,proto3" json:"admin_verification_token,omitempty"`
	// If accept is false then the request will be rejected and a reject reason must be
	// specified. If it is true, then the certificate issuance process will begin.
	Accept        bool   `protobuf:"varint,3,opt,name=accept,proto3" json:"accept,omitempty"`
	RejectReason  string `protobuf:"bytes,4,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewRequest) Reset() {
	*x = ReviewRequest{}
	mi := &file_gds_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRequest) ProtoMessage() {}

func (x *ReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gds_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRequest.ProtoReflect.Descriptor instead.
func (*ReviewRequest) Descriptor() ([]byte, []int) {
	return file_gds_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReviewRequest) GetAdminVerificationToken() string {
	if x != nil {
		return x.AdminVerificationToken
	}
	return ""
}

func (x *ReviewRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

func (x *ReviewRequest) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type ReviewReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If no error is specified, the verify email request was successful
	Error *v1beta1.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// The verification status of the VASP entity.
	Status        v1beta11.VerificationState `protobuf:"varint,2,opt,name=status,proto3,enum=trisa.gds.models.v1beta1.VerificationState" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewReply) Reset() {
	*x = ReviewReply{}
	mi := &file_gds_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewReply) ProtoMessage() {}

func (x *ReviewReply) ProtoReflect() protoreflect.Message {
	mi := &file_gds_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewReply.ProtoReflect.Descriptor instead.
func (*ReviewReply) Descriptor() ([]byte, []int) {
	return file_gds_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewReply) GetError() *v1beta1.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ReviewReply) GetStatus() v1beta11.VerificationState {
	if x != nil {
		return x.Status
	}
	return v1beta11.VerificationState(0)
}

func (x *ReviewReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Resend requests allow extra attempts to resend emails to be made if they were not
// delivered or recieved the first time. This is a routine action that may need to be
// carried out from time to time.
type ResendRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                 // The ID of the VASP to resend emails for
	Type          ResendRequest_ResendType `protobuf:"varint,2,opt,name=type,proto3,enum=gds.admin.v1.ResendRequest_ResendType" json:"type,omitempty"` // The type of message to attempt to resend
	Reason        string                   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                         // If a rejection email, supply the reason for the rejection.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendRequest) Reset() {
	*x = ResendRequest{}
	mi := &file_gds_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendRequest) ProtoMessage() {}

func (x *ResendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gds_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendRequest.ProtoReflect.Descriptor instead.
func (*ResendRequest) Descriptor() ([]byte, []int) {
	return file_gds_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ResendRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResendRequest) GetType() ResendRequest_ResendType {
	if x != nil {
		return x.Type
	}
	return ResendRequest_UNKNOWN
}

func (x *ResendRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ResendReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sent          int64                  `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`      // The number of emails sent
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Any message from the server about status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendReply) Reset() {
	*x = ResendReply{}
	mi := &file_gds_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendReply) ProtoMessage() {}

func (x *ResendReply) ProtoReflect() protoreflect.Message {
	mi := &file_gds_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendReply.ProtoReflect.Descriptor instead.
func (*ResendReply) Descriptor() ([]byte, []int) {
	return file_gds_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ResendReply) GetSent() int64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *ResendReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NoRegistrations       bool                   `protobuf:"varint,1,opt,name=no_registrations,json=noRegistrations,proto3" json:"no_registrations,omitempty"`                     // Ignore counting the registration statuses
	NoCertificateRequests bool                   `protobuf:"varint,2,opt,name=no_certificate_requests,json=noCertificateRequests,proto3" json:"no_certificate_requests,omitempty"` // Ignore counting certificate request statuses
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_gds_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gds_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_gds_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetNoRegistrations() bool {
	if x != nil {
		return x.NoRegistrations
	}
	return false
}

func (x *StatusRequest) GetNoCertificateRequests() bool {
	if x != nil {
		return x.NoCertificateRequests
	}
	return false
}

type StatusReply struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Registrations       map[string]int64       `protobuf:"bytes,1,rep,name=registrations,proto3" json:"registrations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	CertificateRequests map[string]int64       `protobuf:"bytes,2,rep,name=certificate_requests,json=certificateRequests,proto3" json:"certificate_requests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_gds_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_gds_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_gds_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *StatusReply) GetRegistrations() map[string]int64 {
	if x != nil {
		return x.Registrations
	}
	return nil
}

func (x *StatusReply) GetCertificateRequests() map[string]int64 {
	if x != nil {
		return x.CertificateRequests
	}
	return nil
}

var File_gds_admin_v1_admin_proto protoreflect.FileDescriptor

const file_gds_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x18gds/admin/v1/admin.proto\x12\fgds.admin.v1\x1a\x1ftrisa/gds/api/v1beta1/api.proto\x1a%trisa/gds/models/v1beta1/models.proto\"\x96\x01\n" +
	"\rReviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\x18admin_verification_token\x18\x02 \x01(\tR\x16adminVerificationToken\x12\x16\n" +
	"\x06accept\x18\x03 \x01(\bR\x06accept\x12#\n" +
	"\rreject_reason\x18\x04 \x01(\tR\frejectReason\"\xa0\x01\n" +
	"\vReviewReply\x122\n" +
	"\x05error\x18\x01 \x01(\v2\x1c.trisa.gds.api.v1beta1.ErrorR\x05error\x12C\n" +
	"\x06status\x18\x02 \x01(\x0e2+.trisa.gds.models.v1beta1.VerificationStateR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xd0\x01\n" +
	"\rResendRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\x04type\x18\x02 \x01(\x0e2&.gds.admin.v1.ResendRequest.ResendTypeR\x04type\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"[\n" +
	"\n" +
	"ResendType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eVERIFY_CONTACT\x10\x01\x12\n" +
	"\n" +
	"\x06REVIEW\x10\x02\x12\x11\n" +
	"\rDELIVER_CERTS\x10\x03\x12\r\n" +
	"\tREJECTION\x10\x04\";\n" +
	"\vResendReply\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\x03R\x04sent\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"r\n" +
	"\rStatusRequest\x12)\n" +
	"\x10no_registrations\x18\x01 \x01(\bR\x0fnoRegistrations\x126\n" +
	"\x17no_certificate_requests\x18\x02 \x01(\bR\x15noCertificateRequests\"\xd2\x02\n" +
	"\vStatusReply\x12R\n" +
	"\rregistrations\x18\x01 \x03(\v2,.gds.admin.v1.StatusReply.RegistrationsEntryR\rregistrations\x12e\n" +
	"\x14certificate_requests\x18\x02 \x03(\v22.gds.admin.v1.StatusReply.CertificateRequestsEntryR\x13certificateRequests\x1a@\n" +
	"\x12RegistrationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aF\n" +
	"\x18CertificateRequestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xe5\x01\n" +
	"\x17DirectoryAdministration\x12B\n" +
	"\x06Review\x12\x1b.gds.admin.v1.ReviewRequest\x1a\x19.gds.admin.v1.ReviewReply\"\x00\x12B\n" +
	"\x06Resend\x12\x1b.gds.admin.v1.ResendRequest\x1a\x19.gds.admin.v1.ResendReply\"\x00\x12B\n" +
	"\x06Status\x12\x1b.gds.admin.v1.StatusRequest\x1a\x19.gds.admin.v1.StatusReply\"\x00B9Z7github.com/trisacrypto/directory/pkg/gds/admin/v1;adminb\x06proto3"

var (
	file_gds_admin_v1_admin_proto_rawDescOnce sync.Once
	file_gds_admin_v1_admin_proto_rawDescData []byte
)

func file_gds_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_gds_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_gds_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gds_admin_v1_admin_proto_rawDesc), len(file_gds_admin_v1_admin_proto_rawDesc)))
	})
	return file_gds_admin_v1_admin_proto_rawDescData
}

var file_gds_admin_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gds_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gds_admin_v1_admin_proto_goTypes = []any{
	(ResendRequest_ResendType)(0),   // 0: gds.admin.v1.ResendRequest.ResendType
	(*ReviewRequest)(nil),           // 1: gds.admin.v1.ReviewRequest
	(*ReviewReply)(nil),             // 2: gds.admin.v1.ReviewReply
	(*ResendRequest)(nil),           // 3: gds.admin.v1.ResendRequest
	(*ResendReply)(nil),             // 4: gds.admin.v1.ResendReply
	(*StatusRequest)(nil),           // 5: gds.admin.v1.StatusRequest
	(*StatusReply)(nil),             // 6: gds.admin.v1.StatusReply
	nil,                             // 7: gds.admin.v1.StatusReply.RegistrationsEntry
	nil,                             // 8: gds.admin.v1.StatusReply.CertificateRequestsEntry
	(*v1beta1.Error)(nil),           // 9: trisa.gds.api.v1beta1.Error
	(v1beta11.VerificationState)(0), // 10: trisa.gds.models.v1beta1.VerificationState
}
var file_gds_admin_v1_admin_proto_depIdxs = []int32{
	9,  // 0: gds.admin.v1.ReviewReply.error:type_name -> trisa.gds.api.v1beta1.Error
	10, // 1: gds.admin.v1.ReviewReply.status:type_name -> trisa.gds.models.v1beta1.VerificationState
	0,  // 2: gds.admin.v1.ResendRequest.type:type_name -> gds.admin.v1.ResendRequest.ResendType
	7,  // 3: gds.admin.v1.StatusReply.registrations:type_name -> gds.admin.v1.StatusReply.RegistrationsEntry
	8,  // 4: gds.admin.v1.StatusReply.certificate_requests:type_name -> gds.admin.v1.StatusReply.CertificateRequestsEntry
	1,  // 5: gds.admin.v1.DirectoryAdministration.Review:input_type -> gds.admin.v1.ReviewRequest
	3,  // 6: gds.admin.v1.DirectoryAdministration.Resend:input_type -> gds.admin.v1.ResendRequest
	5,  // 7: gds.admin.v1.DirectoryAdministration.Status:input_type -> gds.admin.v1.StatusRequest
	2,  // 8: gds.admin.v1.DirectoryAdministration.Review:output_type -> gds.admin.v1.ReviewReply
	4,  // 9: gds.admin.v1.DirectoryAdministration.Resend:output_type -> gds.admin.v1.ResendReply
	6,  // 10: gds.admin.v1.DirectoryAdministration.Status:output_type -> gds.admin.v1.StatusReply
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gds_admin_v1_admin_proto_init() }
func file_gds_admin_v1_admin_proto_init() {
	if File_gds_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gds_admin_v1_admin_proto_rawDesc), len(file_gds_admin_v1_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gds_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_gds_admin_v1_admin_proto_depIdxs,
		EnumInfos:         file_gds_admin_v1_admin_proto_enumTypes,
		MessageInfos:      file_gds_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_gds_admin_v1_admin_proto = out.File
	file_gds_admin_v1_admin_proto_goTypes = nil
	file_gds_admin_v1_admin_proto_depIdxs = nil
}
