// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: trtl/v1/trtl.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Options       *Options               `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRequest) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"` // will only be supplied if return_meta=true in options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{1}
}

func (x *GetReply) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetReply) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Options       *Options               `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutRequest) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type PutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"` // will only be supplied if return_meta=true in options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutReply) Reset() {
	*x = PutReply{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReply) ProtoMessage() {}

func (x *PutReply) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReply.ProtoReflect.Descriptor instead.
func (*PutReply) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{3}
}

func (x *PutReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutReply) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Options       *Options               `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"` // if return_meta=true then the meta of the version deleted is returned
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteRequest) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type DeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"` // will only be supplied if return_meta=true in options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReply) Reset() {
	*x = DeleteReply{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReply) ProtoMessage() {}

func (x *DeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReply.ProtoReflect.Descriptor instead.
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteReply) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type IterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // the prefix to range over, if nil all objects are returned
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Options       *Options               `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IterRequest) Reset() {
	*x = IterRequest{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IterRequest) ProtoMessage() {}

func (x *IterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IterRequest.ProtoReflect.Descriptor instead.
func (*IterRequest) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{6}
}

func (x *IterRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *IterRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IterRequest) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type IterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*KVPair              `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IterReply) Reset() {
	*x = IterReply{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IterReply) ProtoMessage() {}

func (x *IterReply) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IterReply.ProtoReflect.Descriptor instead.
func (*IterReply) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{7}
}

func (x *IterReply) GetValues() []*KVPair {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *IterReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*BatchRequest_Put
	//	*BatchRequest_Delete
	Request       isBatchRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{8}
}

func (x *BatchRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BatchRequest) GetRequest() isBatchRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *BatchRequest) GetPut() *PutRequest {
	if x != nil {
		if x, ok := x.Request.(*BatchRequest_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *BatchRequest) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Request.(*BatchRequest_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isBatchRequest_Request interface {
	isBatchRequest_Request()
}

type BatchRequest_Put struct {
	Put *PutRequest `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}

type BatchRequest_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

func (*BatchRequest_Put) isBatchRequest_Request() {}

func (*BatchRequest_Delete) isBatchRequest_Request() {}

type BatchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    int64                  `protobuf:"varint,1,opt,name=operations,proto3" json:"operations,omitempty"`
	Successful    int64                  `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	Failed        int64                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors        []*BatchReply_Error    `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchReply) Reset() {
	*x = BatchReply{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReply) ProtoMessage() {}

func (x *BatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReply.ProtoReflect.Descriptor instead.
func (*BatchReply) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{9}
}

func (x *BatchReply) GetOperations() int64 {
	if x != nil {
		return x.Operations
	}
	return 0
}

func (x *BatchReply) GetSuccessful() int64 {
	if x != nil {
		return x.Successful
	}
	return 0
}

func (x *BatchReply) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchReply) GetErrors() []*BatchReply_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`                  // the prefix to range over, if nil all objects are returned
	SeekKey       []byte                 `protobuf:"bytes,2,opt,name=seek_key,json=seekKey,proto3" json:"seek_key,omitempty"` // a key to seekto within the prefix (optional)
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Options       *Options               `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorRequest) Reset() {
	*x = CursorRequest{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorRequest) ProtoMessage() {}

func (x *CursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorRequest.ProtoReflect.Descriptor instead.
func (*CursorRequest) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{10}
}

func (x *CursorRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *CursorRequest) GetSeekKey() []byte {
	if x != nil {
		return x.SeekKey
	}
	return nil
}

func (x *CursorRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CursorRequest) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*SyncRequest_Get
	//	*SyncRequest_Put
	//	*SyncRequest_Delete
	//	*SyncRequest_Iter
	Request       isSyncRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{11}
}

func (x *SyncRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SyncRequest) GetRequest() isSyncRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *SyncRequest) GetGet() *GetRequest {
	if x != nil {
		if x, ok := x.Request.(*SyncRequest_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *SyncRequest) GetPut() *PutRequest {
	if x != nil {
		if x, ok := x.Request.(*SyncRequest_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *SyncRequest) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Request.(*SyncRequest_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *SyncRequest) GetIter() *IterRequest {
	if x != nil {
		if x, ok := x.Request.(*SyncRequest_Iter); ok {
			return x.Iter
		}
	}
	return nil
}

type isSyncRequest_Request interface {
	isSyncRequest_Request()
}

type SyncRequest_Get struct {
	Get *GetRequest `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

type SyncRequest_Put struct {
	Put *PutRequest `protobuf:"bytes,3,opt,name=put,proto3,oneof"`
}

type SyncRequest_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

type SyncRequest_Iter struct {
	Iter *IterRequest `protobuf:"bytes,5,opt,name=iter,proto3,oneof"`
}

func (*SyncRequest_Get) isSyncRequest_Request() {}

func (*SyncRequest_Put) isSyncRequest_Request() {}

func (*SyncRequest_Delete) isSyncRequest_Request() {}

func (*SyncRequest_Iter) isSyncRequest_Request() {}

type SyncReply struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Reply:
	//
	//	*SyncReply_Get
	//	*SyncReply_Put
	//	*SyncReply_Delete
	//	*SyncReply_Iter
	Reply         isSyncReply_Reply `protobuf_oneof:"reply"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncReply) Reset() {
	*x = SyncReply{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReply) ProtoMessage() {}

func (x *SyncReply) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReply.ProtoReflect.Descriptor instead.
func (*SyncReply) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{12}
}

func (x *SyncReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SyncReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SyncReply) GetReply() isSyncReply_Reply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *SyncReply) GetGet() *GetReply {
	if x != nil {
		if x, ok := x.Reply.(*SyncReply_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *SyncReply) GetPut() *PutReply {
	if x != nil {
		if x, ok := x.Reply.(*SyncReply_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *SyncReply) GetDelete() *DeleteReply {
	if x != nil {
		if x, ok := x.Reply.(*SyncReply_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *SyncReply) GetIter() *IterReply {
	if x != nil {
		if x, ok := x.Reply.(*SyncReply_Iter); ok {
			return x.Iter
		}
	}
	return nil
}

type isSyncReply_Reply interface {
	isSyncReply_Reply()
}

type SyncReply_Get struct {
	Get *GetReply `protobuf:"bytes,4,opt,name=get,proto3,oneof"`
}

type SyncReply_Put struct {
	Put *PutReply `protobuf:"bytes,5,opt,name=put,proto3,oneof"`
}

type SyncReply_Delete struct {
	Delete *DeleteReply `protobuf:"bytes,6,opt,name=delete,proto3,oneof"`
}

type SyncReply_Iter struct {
	Iter *IterReply `protobuf:"bytes,7,opt,name=iter,proto3,oneof"`
}

func (*SyncReply_Get) isSyncReply_Reply() {}

func (*SyncReply_Put) isSyncReply_Reply() {}

func (*SyncReply_Delete) isSyncReply_Reply() {}

func (*SyncReply_Iter) isSyncReply_Reply() {}

type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`                  // the prefix to range over, if nil all objects are counted
	SeekKey       []byte                 `protobuf:"bytes,2,opt,name=seek_key,json=seekKey,proto3" json:"seek_key,omitempty"` // a key to seekto within the prefix (optional)
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{13}
}

func (x *CountRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *CountRequest) GetSeekKey() []byte {
	if x != nil {
		return x.SeekKey
	}
	return nil
}

func (x *CountRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type CountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       uint64                 `protobuf:"varint,1,opt,name=objects,proto3" json:"objects,omitempty"`                            // the number of objects in the iterator
	KeyBytes      uint64                 `protobuf:"varint,2,opt,name=key_bytes,json=keyBytes,proto3" json:"key_bytes,omitempty"`          // the number of bytes used for keys
	ObjectBytes   uint64                 `protobuf:"varint,3,opt,name=object_bytes,json=objectBytes,proto3" json:"object_bytes,omitempty"` // the number of bytes used for objects
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountReply) Reset() {
	*x = CountReply{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountReply) ProtoMessage() {}

func (x *CountReply) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountReply.ProtoReflect.Descriptor instead.
func (*CountReply) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{14}
}

func (x *CountReply) GetObjects() uint64 {
	if x != nil {
		return x.Objects
	}
	return 0
}

func (x *CountReply) GetKeyBytes() uint64 {
	if x != nil {
		return x.KeyBytes
	}
	return 0
}

func (x *CountReply) GetObjectBytes() uint64 {
	if x != nil {
		return x.ObjectBytes
	}
	return 0
}

type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{15}
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        string                 `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Replica       *ReplicaStatus         `protobuf:"bytes,15,opt,name=replica,proto3" json:"replica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{16}
}

func (x *ServerStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServerStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *ServerStatus) GetReplica() *ReplicaStatus {
	if x != nil {
		return x.Replica
	}
	return nil
}

type ReplicaStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Pid           uint64                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Interval      string                 `protobuf:"bytes,5,opt,name=interval,proto3" json:"interval,omitempty"`
	Sigma         string                 `protobuf:"bytes,6,opt,name=sigma,proto3" json:"sigma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaStatus) Reset() {
	*x = ReplicaStatus{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaStatus) ProtoMessage() {}

func (x *ReplicaStatus) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaStatus.ProtoReflect.Descriptor instead.
func (*ReplicaStatus) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{17}
}

func (x *ReplicaStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ReplicaStatus) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ReplicaStatus) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ReplicaStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReplicaStatus) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *ReplicaStatus) GetSigma() string {
	if x != nil {
		return x.Sigma
	}
	return ""
}

// Options conditions all accesses to trtl, e.g. there are not different structs for
// Get vs Put options. The semantics of each option depends on the type of request.
type Options struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnMeta    bool                   `protobuf:"varint,1,opt,name=return_meta,json=returnMeta,proto3" json:"return_meta,omitempty"`         // generally, return the version information for the object in the response
	IterNoKeys    bool                   `protobuf:"varint,2,opt,name=iter_no_keys,json=iterNoKeys,proto3" json:"iter_no_keys,omitempty"`       // do not include keys in an Iter or Cursor response, to reduce data transfer load
	IterNoValues  bool                   `protobuf:"varint,3,opt,name=iter_no_values,json=iterNoValues,proto3" json:"iter_no_values,omitempty"` // do not include values in an Iter or Cursor response, to reduce data transfer load
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`             // specify the page token to fetch the next page of results
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`               // specify the number of results per page, cannot change between page requests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{18}
}

func (x *Options) GetReturnMeta() bool {
	if x != nil {
		return x.ReturnMeta
	}
	return false
}

func (x *Options) GetIterNoKeys() bool {
	if x != nil {
		return x.IterNoKeys
	}
	return false
}

func (x *Options) GetIterNoValues() bool {
	if x != nil {
		return x.IterNoValues
	}
	return false
}

func (x *Options) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *Options) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// A key/value pair that is returned in Iter and Cursor requests
type KVPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVPair) Reset() {
	*x = KVPair{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPair) ProtoMessage() {}

func (x *KVPair) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPair.ProtoReflect.Descriptor instead.
func (*KVPair) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{19}
}

func (x *KVPair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KVPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KVPair) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KVPair) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Meta is a simplified representation of the honu.object.v1.Object metadata that trtl
// actually stores. The simplification is intended to return non-nested data version
// information to the user in a read-only fashion.
type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`             // the key that the metadata describes
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"` // a unique namespace of the key, usually a prefix
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`       // the region in which the data originated
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`         // the name of the replica where the data originated
	Version       *Version               `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`     // the current conflict-free version of the data
	Parent        *Version               `protobuf:"bytes,6,opt,name=parent,proto3" json:"parent,omitempty"`       // the version the current data was was derived from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{20}
}

func (x *Meta) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Meta) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Meta) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Meta) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Meta) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Meta) GetParent() *Version {
	if x != nil {
		return x.Parent
	}
	return nil
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint64                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`         // process id, used for conflict-free version comparisons
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // a monotonically increasing scalar that describes changes in the record
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`    // the region where the version originated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{21}
}

func (x *Version) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Version) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Version) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type BatchReply_Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchReply_Error) Reset() {
	*x = BatchReply_Error{}
	mi := &file_trtl_v1_trtl_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReply_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReply_Error) ProtoMessage() {}

func (x *BatchReply_Error) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_v1_trtl_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReply_Error.ProtoReflect.Descriptor instead.
func (*BatchReply_Error) Descriptor() ([]byte, []int) {
	return file_trtl_v1_trtl_proto_rawDescGZIP(), []int{9, 0}
}

func (x *BatchReply_Error) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BatchReply_Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_trtl_v1_trtl_proto protoreflect.FileDescriptor

const file_trtl_v1_trtl_proto_rawDesc = "" +
	"\n" +
	"\x12trtl/v1/trtl.proto\x12\atrtl.v1\"h\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12*\n" +
	"\aoptions\x18\x03 \x01(\v2\x10.trtl.v1.OptionsR\aoptions\"C\n" +
	"\bGetReply\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12!\n" +
	"\x04meta\x18\x02 \x01(\v2\r.trtl.v1.MetaR\x04meta\"~\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12*\n" +
	"\aoptions\x18\x04 \x01(\v2\x10.trtl.v1.OptionsR\aoptions\"G\n" +
	"\bPutReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x04meta\x18\x02 \x01(\v2\r.trtl.v1.MetaR\x04meta\"k\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12*\n" +
	"\aoptions\x18\x03 \x01(\v2\x10.trtl.v1.OptionsR\aoptions\"J\n" +
	"\vDeleteReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x04meta\x18\x02 \x01(\v2\r.trtl.v1.MetaR\x04meta\"o\n" +
	"\vIterRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\fR\x06prefix\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12*\n" +
	"\aoptions\x18\x03 \x01(\v2\x10.trtl.v1.OptionsR\aoptions\"\\\n" +
	"\tIterReply\x12'\n" +
	"\x06values\x18\x01 \x03(\v2\x0f.trtl.v1.KVPairR\x06values\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x84\x01\n" +
	"\fBatchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x03put\x18\x02 \x01(\v2\x13.trtl.v1.PutRequestH\x00R\x03put\x120\n" +
	"\x06delete\x18\x03 \x01(\v2\x16.trtl.v1.DeleteRequestH\x00R\x06deleteB\t\n" +
	"\arequest\"\xc6\x01\n" +
	"\n" +
	"BatchReply\x12\x1e\n" +
	"\n" +
	"operations\x18\x01 \x01(\x03R\n" +
	"operations\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\x03R\n" +
	"successful\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x03R\x06failed\x121\n" +
	"\x06errors\x18\x04 \x03(\v2\x19.trtl.v1.BatchReply.ErrorR\x06errors\x1a-\n" +
	"\x05Error\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8c\x01\n" +
	"\rCursorRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\fR\x06prefix\x12\x19\n" +
	"\bseek_key\x18\x02 \x01(\fR\aseekKey\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12*\n" +
	"\aoptions\x18\x04 \x01(\v2\x10.trtl.v1.OptionsR\aoptions\"\xd8\x01\n" +
	"\vSyncRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x03get\x18\x02 \x01(\v2\x13.trtl.v1.GetRequestH\x00R\x03get\x12'\n" +
	"\x03put\x18\x03 \x01(\v2\x13.trtl.v1.PutRequestH\x00R\x03put\x120\n" +
	"\x06delete\x18\x04 \x01(\v2\x16.trtl.v1.DeleteRequestH\x00R\x06delete\x12*\n" +
	"\x04iter\x18\x05 \x01(\v2\x14.trtl.v1.IterRequestH\x00R\x04iterB\t\n" +
	"\arequest\"\xfc\x01\n" +
	"\tSyncReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12%\n" +
	"\x03get\x18\x04 \x01(\v2\x11.trtl.v1.GetReplyH\x00R\x03get\x12%\n" +
	"\x03put\x18\x05 \x01(\v2\x11.trtl.v1.PutReplyH\x00R\x03put\x12.\n" +
	"\x06delete\x18\x06 \x01(\v2\x14.trtl.v1.DeleteReplyH\x00R\x06delete\x12(\n" +
	"\x04iter\x18\a \x01(\v2\x12.trtl.v1.IterReplyH\x00R\x04iterB\a\n" +
	"\x05reply\"_\n" +
	"\fCountRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\fR\x06prefix\x12\x19\n" +
	"\bseek_key\x18\x02 \x01(\fR\aseekKey\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"f\n" +
	"\n" +
	"CountReply\x12\x18\n" +
	"\aobjects\x18\x01 \x01(\x04R\aobjects\x12\x1b\n" +
	"\tkey_bytes\x18\x02 \x01(\x04R\bkeyBytes\x12!\n" +
	"\fobject_bytes\x18\x03 \x01(\x04R\vobjectBytes\"\r\n" +
	"\vHealthCheck\"\x8a\x01\n" +
	"\fServerStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\tR\x06uptime\x120\n" +
	"\areplica\x18\x0f \x01(\v2\x16.trtl.v1.ReplicaStatusR\areplica\"\x99\x01\n" +
	"\rReplicaStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x04R\x03pid\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\binterval\x18\x05 \x01(\tR\binterval\x12\x14\n" +
	"\x05sigma\x18\x06 \x01(\tR\x05sigma\"\xae\x01\n" +
	"\aOptions\x12\x1f\n" +
	"\vreturn_meta\x18\x01 \x01(\bR\n" +
	"returnMeta\x12 \n" +
	"\fiter_no_keys\x18\x02 \x01(\bR\n" +
	"iterNoKeys\x12$\n" +
	"\x0eiter_no_values\x18\x03 \x01(\bR\fiterNoValues\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"q\n" +
	"\x06KVPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12!\n" +
	"\x04meta\x18\x04 \x01(\v2\r.trtl.v1.MetaR\x04meta\"\xba\x01\n" +
	"\x04Meta\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12*\n" +
	"\aversion\x18\x05 \x01(\v2\x10.trtl.v1.VersionR\aversion\x12(\n" +
	"\x06parent\x18\x06 \x01(\v2\x10.trtl.v1.VersionR\x06parent\"M\n" +
	"\aVersion\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x04R\x03pid\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region2\xee\x03\n" +
	"\x04Trtl\x12/\n" +
	"\x03Get\x12\x13.trtl.v1.GetRequest\x1a\x11.trtl.v1.GetReply\"\x00\x12/\n" +
	"\x03Put\x12\x13.trtl.v1.PutRequest\x1a\x11.trtl.v1.PutReply\"\x00\x128\n" +
	"\x06Delete\x12\x16.trtl.v1.DeleteRequest\x1a\x14.trtl.v1.DeleteReply\"\x00\x122\n" +
	"\x04Iter\x12\x14.trtl.v1.IterRequest\x1a\x12.trtl.v1.IterReply\"\x00\x127\n" +
	"\x05Batch\x12\x15.trtl.v1.BatchRequest\x1a\x13.trtl.v1.BatchReply\"\x00(\x01\x125\n" +
	"\x06Cursor\x12\x16.trtl.v1.CursorRequest\x1a\x0f.trtl.v1.KVPair\"\x000\x01\x126\n" +
	"\x04Sync\x12\x14.trtl.v1.SyncRequest\x1a\x12.trtl.v1.SyncReply\"\x00(\x010\x01\x125\n" +
	"\x05Count\x12\x15.trtl.v1.CountRequest\x1a\x13.trtl.v1.CountReply\"\x00\x127\n" +
	"\x06Status\x12\x14.trtl.v1.HealthCheck\x1a\x15.trtl.v1.ServerStatus\"\x00B4Z2github.com/trisacrypto/directory/pkg/trtl/pb/v1;pbb\x06proto3"

var (
	file_trtl_v1_trtl_proto_rawDescOnce sync.Once
	file_trtl_v1_trtl_proto_rawDescData []byte
)

func file_trtl_v1_trtl_proto_rawDescGZIP() []byte {
	file_trtl_v1_trtl_proto_rawDescOnce.Do(func() {
		file_trtl_v1_trtl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trtl_v1_trtl_proto_rawDesc), len(file_trtl_v1_trtl_proto_rawDesc)))
	})
	return file_trtl_v1_trtl_proto_rawDescData
}

var file_trtl_v1_trtl_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_trtl_v1_trtl_proto_goTypes = []any{
	(*GetRequest)(nil),       // 0: trtl.v1.GetRequest
	(*GetReply)(nil),         // 1: trtl.v1.GetReply
	(*PutRequest)(nil),       // 2: trtl.v1.PutRequest
	(*PutReply)(nil),         // 3: trtl.v1.PutReply
	(*DeleteRequest)(nil),    // 4: trtl.v1.DeleteRequest
	(*DeleteReply)(nil),      // 5: trtl.v1.DeleteReply
	(*IterRequest)(nil),      // 6: trtl.v1.IterRequest
	(*IterReply)(nil),        // 7: trtl.v1.IterReply
	(*BatchRequest)(nil),     // 8: trtl.v1.BatchRequest
	(*BatchReply)(nil),       // 9: trtl.v1.BatchReply
	(*CursorRequest)(nil),    // 10: trtl.v1.CursorRequest
	(*SyncRequest)(nil),      // 11: trtl.v1.SyncRequest
	(*SyncReply)(nil),        // 12: trtl.v1.SyncReply
	(*CountRequest)(nil),     // 13: trtl.v1.CountRequest
	(*CountReply)(nil),       // 14: trtl.v1.CountReply
	(*HealthCheck)(nil),      // 15: trtl.v1.HealthCheck
	(*ServerStatus)(nil),     // 16: trtl.v1.ServerStatus
	(*ReplicaStatus)(nil),    // 17: trtl.v1.ReplicaStatus
	(*Options)(nil),          // 18: trtl.v1.Options
	(*KVPair)(nil),           // 19: trtl.v1.KVPair
	(*Meta)(nil),             // 20: trtl.v1.Meta
	(*Version)(nil),          // 21: trtl.v1.Version
	(*BatchReply_Error)(nil), // 22: trtl.v1.BatchReply.Error
}
var file_trtl_v1_trtl_proto_depIdxs = []int32{
	18, // 0: trtl.v1.GetRequest.options:type_name -> trtl.v1.Options
	20, // 1: trtl.v1.GetReply.meta:type_name -> trtl.v1.Meta
	18, // 2: trtl.v1.PutRequest.options:type_name -> trtl.v1.Options
	20, // 3: trtl.v1.PutReply.meta:type_name -> trtl.v1.Meta
	18, // 4: trtl.v1.DeleteRequest.options:type_name -> trtl.v1.Options
	20, // 5: trtl.v1.DeleteReply.meta:type_name -> trtl.v1.Meta
	18, // 6: trtl.v1.IterRequest.options:type_name -> trtl.v1.Options
	19, // 7: trtl.v1.IterReply.values:type_name -> trtl.v1.KVPair
	2,  // 8: trtl.v1.BatchRequest.put:type_name -> trtl.v1.PutRequest
	4,  // 9: trtl.v1.BatchRequest.delete:type_name -> trtl.v1.DeleteRequest
	22, // 10: trtl.v1.BatchReply.errors:type_name -> trtl.v1.BatchReply.Error
	18, // 11: trtl.v1.CursorRequest.options:type_name -> trtl.v1.Options
	0,  // 12: trtl.v1.SyncRequest.get:type_name -> trtl.v1.GetRequest
	2,  // 13: trtl.v1.SyncRequest.put:type_name -> trtl.v1.PutRequest
	4,  // 14: trtl.v1.SyncRequest.delete:type_name -> trtl.v1.DeleteRequest
	6,  // 15: trtl.v1.SyncRequest.iter:type_name -> trtl.v1.IterRequest
	1,  // 16: trtl.v1.SyncReply.get:type_name -> trtl.v1.GetReply
	3,  // 17: trtl.v1.SyncReply.put:type_name -> trtl.v1.PutReply
	5,  // 18: trtl.v1.SyncReply.delete:type_name -> trtl.v1.DeleteReply
	7,  // 19: trtl.v1.SyncReply.iter:type_name -> trtl.v1.IterReply
	17, // 20: trtl.v1.ServerStatus.replica:type_name -> trtl.v1.ReplicaStatus
	20, // 21: trtl.v1.KVPair.meta:type_name -> trtl.v1.Meta
	21, // 22: trtl.v1.Meta.version:type_name -> trtl.v1.Version
	21, // 23: trtl.v1.Meta.parent:type_name -> trtl.v1.Version
	0,  // 24: trtl.v1.Trtl.Get:input_type -> trtl.v1.GetRequest
	2,  // 25: trtl.v1.Trtl.Put:input_type -> trtl.v1.PutRequest
	4,  // 26: trtl.v1.Trtl.Delete:input_type -> trtl.v1.DeleteRequest
	6,  // 27: trtl.v1.Trtl.Iter:input_type -> trtl.v1.IterRequest
	8,  // 28: trtl.v1.Trtl.Batch:input_type -> trtl.v1.BatchRequest
	10, // 29: trtl.v1.Trtl.Cursor:input_type -> trtl.v1.CursorRequest
	11, // 30: trtl.v1.Trtl.Sync:input_type -> trtl.v1.SyncRequest
	13, // 31: trtl.v1.Trtl.Count:input_type -> trtl.v1.CountRequest
	15, // 32: trtl.v1.Trtl.Status:input_type -> trtl.v1.HealthCheck
	1,  // 33: trtl.v1.Trtl.Get:output_type -> trtl.v1.GetReply
	3,  // 34: trtl.v1.Trtl.Put:output_type -> trtl.v1.PutReply
	5,  // 35: trtl.v1.Trtl.Delete:output_type -> trtl.v1.DeleteReply
	7,  // 36: trtl.v1.Trtl.Iter:output_type -> trtl.v1.IterReply
	9,  // 37: trtl.v1.Trtl.Batch:output_type -> trtl.v1.BatchReply
	19, // 38: trtl.v1.Trtl.Cursor:output_type -> trtl.v1.KVPair
	12, // 39: trtl.v1.Trtl.Sync:output_type -> trtl.v1.SyncReply
	14, // 40: trtl.v1.Trtl.Count:output_type -> trtl.v1.CountReply
	16, // 41: trtl.v1.Trtl.Status:output_type -> trtl.v1.ServerStatus
	33, // [33:42] is the sub-list for method output_type
	24, // [24:33] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_trtl_v1_trtl_proto_init() }
func file_trtl_v1_trtl_proto_init() {
	if File_trtl_v1_trtl_proto != nil {
		return
	}
	file_trtl_v1_trtl_proto_msgTypes[8].OneofWrappers = []any{
		(*BatchRequest_Put)(nil),
		(*BatchRequest_Delete)(nil),
	}
	file_trtl_v1_trtl_proto_msgTypes[11].OneofWrappers = []any{
		(*SyncRequest_Get)(nil),
		(*SyncRequest_Put)(nil),
		(*SyncRequest_Delete)(nil),
		(*SyncRequest_Iter)(nil),
	}
	file_trtl_v1_trtl_proto_msgTypes[12].OneofWrappers = []any{
		(*SyncReply_Get)(nil),
		(*SyncReply_Put)(nil),
		(*SyncReply_Delete)(nil),
		(*SyncReply_Iter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trtl_v1_trtl_proto_rawDesc), len(file_trtl_v1_trtl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trtl_v1_trtl_proto_goTypes,
		DependencyIndexes: file_trtl_v1_trtl_proto_depIdxs,
		MessageInfos:      file_trtl_v1_trtl_proto_msgTypes,
	}.Build()
	File_trtl_v1_trtl_proto = out.File
	file_trtl_v1_trtl_proto_goTypes = nil
	file_trtl_v1_trtl_proto_depIdxs = nil
}
