// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: trtl/peers/v1/peers.proto

package peers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Peer contains metadata about how to connect to remote peers in the directory service
// network. This message services as a data-transfer and exchange mechanism for dynamic
// networks with changing membership.
type Peer struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`        // the process id of the peer must be unique in the network; used for distributed versions
	Addr   string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`     // the network address to connect to the peer on (don't forget the port!)
	Name   string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`     // optional - a unique, human readable name for the peer
	Region string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"` // optional? - the region the peer is running in
	// Logging information timestamps
	Created  string `protobuf:"bytes,9,opt,name=created,proto3" json:"created,omitempty"`
	Modified string `protobuf:"bytes,10,opt,name=modified,proto3" json:"modified,omitempty"`
	// extra information that might be relevant to process-specific functions; e.g. for
	// specific clouds or data that's been parsed (optional).
	Extra         map[string]string `protobuf:"bytes,14,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_trtl_peers_v1_peers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_peers_v1_peers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_trtl_peers_v1_peers_proto_rawDescGZIP(), []int{0}
}

func (x *Peer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Peer) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Peer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Peer) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Peer) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Peer) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

func (x *Peer) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// Used to filter the peers that are returned. If no filters are specified then all
// known peers on the remote replica are returned.
type PeersFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        []string               `protobuf:"bytes,1,rep,name=region,proto3" json:"region,omitempty"`                            // Specify the region(s) to return the peers for. Only effects PeersList not PeersStatus
	StatusOnly    bool                   `protobuf:"varint,2,opt,name=status_only,json=statusOnly,proto3" json:"status_only,omitempty"` // Return only the peers status, not a list of peers.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersFilter) Reset() {
	*x = PeersFilter{}
	mi := &file_trtl_peers_v1_peers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersFilter) ProtoMessage() {}

func (x *PeersFilter) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_peers_v1_peers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersFilter.ProtoReflect.Descriptor instead.
func (*PeersFilter) Descriptor() ([]byte, []int) {
	return file_trtl_peers_v1_peers_proto_rawDescGZIP(), []int{1}
}

func (x *PeersFilter) GetRegion() []string {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *PeersFilter) GetStatusOnly() bool {
	if x != nil {
		return x.StatusOnly
	}
	return false
}

// Returns the list of peers currently known to the replica and its peer management status.
type PeersList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	Status        *PeersStatus           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersList) Reset() {
	*x = PeersList{}
	mi := &file_trtl_peers_v1_peers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersList) ProtoMessage() {}

func (x *PeersList) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_peers_v1_peers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersList.ProtoReflect.Descriptor instead.
func (*PeersList) Descriptor() ([]byte, []int) {
	return file_trtl_peers_v1_peers_proto_rawDescGZIP(), []int{2}
}

func (x *PeersList) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PeersList) GetStatus() *PeersStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// A response to a peer management command that describes the current state of the network.
type PeersStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NetworkSize         int64                  `protobuf:"varint,1,opt,name=network_size,json=networkSize,proto3" json:"network_size,omitempty"`                                                // The total number of peers known to the replica (including itself)
	Regions             map[string]int64       `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // The number of peers known to the replica per known region
	LastSynchronization string                 `protobuf:"bytes,3,opt,name=last_synchronization,json=lastSynchronization,proto3" json:"last_synchronization,omitempty"`                         // The timestamp of the last synchronization that exchanged data
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PeersStatus) Reset() {
	*x = PeersStatus{}
	mi := &file_trtl_peers_v1_peers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersStatus) ProtoMessage() {}

func (x *PeersStatus) ProtoReflect() protoreflect.Message {
	mi := &file_trtl_peers_v1_peers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersStatus.ProtoReflect.Descriptor instead.
func (*PeersStatus) Descriptor() ([]byte, []int) {
	return file_trtl_peers_v1_peers_proto_rawDescGZIP(), []int{3}
}

func (x *PeersStatus) GetNetworkSize() int64 {
	if x != nil {
		return x.NetworkSize
	}
	return 0
}

func (x *PeersStatus) GetRegions() map[string]int64 {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *PeersStatus) GetLastSynchronization() string {
	if x != nil {
		return x.LastSynchronization
	}
	return ""
}

var File_trtl_peers_v1_peers_proto protoreflect.FileDescriptor

const file_trtl_peers_v1_peers_proto_rawDesc = "" +
	"\n" +
	"\x19trtl/peers/v1/peers.proto\x12\rtrtl.peers.v1\"\xfc\x01\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x18\n" +
	"\acreated\x18\t \x01(\tR\acreated\x12\x1a\n" +
	"\bmodified\x18\n" +
	" \x01(\tR\bmodified\x124\n" +
	"\x05extra\x18\x0e \x03(\v2\x1e.trtl.peers.v1.Peer.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\vPeersFilter\x12\x16\n" +
	"\x06region\x18\x01 \x03(\tR\x06region\x12\x1f\n" +
	"\vstatus_only\x18\x02 \x01(\bR\n" +
	"statusOnly\"j\n" +
	"\tPeersList\x12)\n" +
	"\x05peers\x18\x01 \x03(\v2\x13.trtl.peers.v1.PeerR\x05peers\x122\n" +
	"\x06status\x18\x02 \x01(\v2\x1a.trtl.peers.v1.PeersStatusR\x06status\"\xe2\x01\n" +
	"\vPeersStatus\x12!\n" +
	"\fnetwork_size\x18\x01 \x01(\x03R\vnetworkSize\x12A\n" +
	"\aregions\x18\x02 \x03(\v2'.trtl.peers.v1.PeersStatus.RegionsEntryR\aregions\x121\n" +
	"\x14last_synchronization\x18\x03 \x01(\tR\x13lastSynchronization\x1a:\n" +
	"\fRegionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xd1\x01\n" +
	"\x0ePeerManagement\x12B\n" +
	"\bGetPeers\x12\x1a.trtl.peers.v1.PeersFilter\x1a\x18.trtl.peers.v1.PeersList\"\x00\x12=\n" +
	"\bAddPeers\x12\x13.trtl.peers.v1.Peer\x1a\x1a.trtl.peers.v1.PeersStatus\"\x00\x12<\n" +
	"\aRmPeers\x12\x13.trtl.peers.v1.Peer\x1a\x1a.trtl.peers.v1.PeersStatus\"\x00B:Z8github.com/trisacrypto/directory/pkg/trtl/peers/v1;peersb\x06proto3"

var (
	file_trtl_peers_v1_peers_proto_rawDescOnce sync.Once
	file_trtl_peers_v1_peers_proto_rawDescData []byte
)

func file_trtl_peers_v1_peers_proto_rawDescGZIP() []byte {
	file_trtl_peers_v1_peers_proto_rawDescOnce.Do(func() {
		file_trtl_peers_v1_peers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trtl_peers_v1_peers_proto_rawDesc), len(file_trtl_peers_v1_peers_proto_rawDesc)))
	})
	return file_trtl_peers_v1_peers_proto_rawDescData
}

var file_trtl_peers_v1_peers_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_trtl_peers_v1_peers_proto_goTypes = []any{
	(*Peer)(nil),        // 0: trtl.peers.v1.Peer
	(*PeersFilter)(nil), // 1: trtl.peers.v1.PeersFilter
	(*PeersList)(nil),   // 2: trtl.peers.v1.PeersList
	(*PeersStatus)(nil), // 3: trtl.peers.v1.PeersStatus
	nil,                 // 4: trtl.peers.v1.Peer.ExtraEntry
	nil,                 // 5: trtl.peers.v1.PeersStatus.RegionsEntry
}
var file_trtl_peers_v1_peers_proto_depIdxs = []int32{
	4, // 0: trtl.peers.v1.Peer.extra:type_name -> trtl.peers.v1.Peer.ExtraEntry
	0, // 1: trtl.peers.v1.PeersList.peers:type_name -> trtl.peers.v1.Peer
	3, // 2: trtl.peers.v1.PeersList.status:type_name -> trtl.peers.v1.PeersStatus
	5, // 3: trtl.peers.v1.PeersStatus.regions:type_name -> trtl.peers.v1.PeersStatus.RegionsEntry
	1, // 4: trtl.peers.v1.PeerManagement.GetPeers:input_type -> trtl.peers.v1.PeersFilter
	0, // 5: trtl.peers.v1.PeerManagement.AddPeers:input_type -> trtl.peers.v1.Peer
	0, // 6: trtl.peers.v1.PeerManagement.RmPeers:input_type -> trtl.peers.v1.Peer
	2, // 7: trtl.peers.v1.PeerManagement.GetPeers:output_type -> trtl.peers.v1.PeersList
	3, // 8: trtl.peers.v1.PeerManagement.AddPeers:output_type -> trtl.peers.v1.PeersStatus
	3, // 9: trtl.peers.v1.PeerManagement.RmPeers:output_type -> trtl.peers.v1.PeersStatus
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_trtl_peers_v1_peers_proto_init() }
func file_trtl_peers_v1_peers_proto_init() {
	if File_trtl_peers_v1_peers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trtl_peers_v1_peers_proto_rawDesc), len(file_trtl_peers_v1_peers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trtl_peers_v1_peers_proto_goTypes,
		DependencyIndexes: file_trtl_peers_v1_peers_proto_depIdxs,
		MessageInfos:      file_trtl_peers_v1_peers_proto_msgTypes,
	}.Build()
	File_trtl_peers_v1_peers_proto = out.File
	file_trtl_peers_v1_peers_proto_goTypes = nil
	file_trtl_peers_v1_peers_proto_depIdxs = nil
}
