# .github/workflows/gcr-cleaner.yaml
name: GCR Cleanup
on:
  # runs daily or on manual invocation
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:

jobs:
  gcr-cleaner:
    runs-on: 'ubuntu-latest'
    steps:
      # configure based on registries
      - name: Login to GCR
        uses: 'docker/login-action@v1'
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_SERVICE_ACCOUNT }}

      - name: Login to Docker Hub
        uses: 'docker/login-action@v1'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # customized based on the gcr-cleaner flags
      # -repo - list of repo to clean (required)
      # -grace - relative duration in which to ignore references, refs newer than duration will not be deleted
      # -keep - minimum number of images to keep, will not consider images inside the grace duration
      # -dry_run - if set to true, will not delete anything and outputs what would have been deleted
      # -recursive - if set to true, will recursively search all child repositories
      - name: Clean Registries
        uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
              -repo=gcr.io/trisa-gds/
              -repo=docker.io/trisa/
              -grace=90d
              -keep=16
              -dry-run=True
              -recursive=True