# .github/workflows/gcr-cleaner.yaml
name: GCR Cleanup
on:
  # runs daily or on manual invocation
  schedule:
    - cron: "0 0 */1 * *"
  workflow_dispatch:

jobs:
  gcr-cleaner:
    runs-on: "ubuntu-latest"
    steps:
      # configure based on registries
      - name: Login to GCR
        uses: "docker/login-action@v2"
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_SERVICE_ACCOUNT }}

      # customized based on the gcr-cleaner flags
      # -repo - list of repo to clean (required)
      # -grace - relative duration in which to ignore references, refs newer than duration will not be deleted
      # -keep - minimum number of images to keep, will not consider images inside the grace duration
      # -dry_run - if set to true, will not delete anything and outputs what would have been deleted
      # -recursive - if set to true, will recursively search all child repositories
      # 2160h = 90 days.
      - name: Clean GCR Registry
        uses: "docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli"
        env:
          GCRCLEANER_LOG: debug
          GOOGLE_PROJECT: trisa-gds
        with:
          args: >-
            -repo=gcr.io/trisa-gds/cathy
            -repo=gcr.io/trisa-gds/demo-bff
            -repo=gcr.io/trisa-gds/demo-npm
            -repo=gcr.io/trisa-gds/gds
            -repo=gcr.io/trisa-gds/gds-admin-ui
            -repo=gcr.io/trisa-gds/gds-bff
            -repo=gcr.io/trisa-gds/gds-staging-admin-ui
            -repo=gcr.io/trisa-gds/gds-staging-testnet-admin-ui
            -repo=gcr.io/trisa-gds/gds-staging-user-ui
            -repo=gcr.io/trisa-gds/gds-testnet-admin-ui
            -repo=gcr.io/trisa-gds/gds-testnet-ui
            -repo=gcr.io/trisa-gds/gds-ui
            -repo=gcr.io/trisa-gds/gds-user-ui
            -repo=gcr.io/trisa-gds/geoping
            -repo=gcr.io/trisa-gds/grpc-proxy
            -repo=gcr.io/trisa-gds/maintenance
            -repo=gcr.io/trisa-gds/placeholder
            -repo=gcr.io/trisa-gds/rvasp
            -repo=gcr.io/trisa-gds/rvasp-alice
            -repo=gcr.io/trisa-gds/rvasp-bob
            -repo=gcr.io/trisa-gds/rvasp-evil
            -repo=gcr.io/trisa-gds/rvasp-migrate
            -repo=gcr.io/trisa-gds/trisarl
            -repo=gcr.io/trisa-gds/trtl
            -repo=gcr.io/trisa-gds/trtl-init
            -repo=gcr.io/trisa-gds/trtlsim
            -grace=2160h
            -keep=16
            -dry-run=True

  docker-cleaner:
    runs-on: "ubuntu-latest"
    steps:
      # configure based on registries
      - name: Login to Docker
        uses: "docker/login-action@v2"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # customized based on the gcr-cleaner flags
      # -repo - list of repo to clean (required)
      # -grace - relative duration in which to ignore references, refs newer than duration will not be deleted
      # -keep - minimum number of images to keep, will not consider images inside the grace duration
      # -dry_run - if set to true, will not delete anything and outputs what would have been deleted
      # -recursive - if set to true, will recursively search all child repositories
      # 2160h = 90 days.
      - name: Clean Docker Registry
        uses: "docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli"
        with:
          args: >-
            -repo=us-docker.pkg.dev/trisa/gds-testnet-admin-ui
            -repo=us-docker.pkg.dev/trisa/gds-user-ui
            -repo=us-docker.pkg.dev/trisa/gds-staging-testnet-admin-ui
            -repo=us-docker.pkg.dev/trisa/gds-staging-user-ui
            -repo=us-docker.pkg.dev/trisa/gds-staging-admin-ui
            -repo=us-docker.pkg.dev/trisa/gds-staging-admin-ui
            -repo=us-docker.pkg.dev/trisa/cathy
            -repo=us-docker.pkg.dev/trisa/gds-bff
            -repo=us-docker.pkg.dev/trisa/gds
            -repo=us-docker.pkg.dev/trisa/trtl
            -repo=us-docker.pkg.dev/trisa/maintenance
            -repo=us-docker.pkg.dev/trisa/trtl-init
            -repo=us-docker.pkg.dev/trisa/rvasp
            -repo=us-docker.pkg.dev/trisa/rvasp-migrate
            -repo=us-docker.pkg.dev/trisa/trtlsim
            -repo=us-docker.pkg.dev/trisa/placeholder
            -repo=us-docker.pkg.dev/trisa/grpc-proxy
            -repo=us-docker.pkg.dev/trisa/gds-ui
            -repo=us-docker.pkg.dev/trisa/gds-testnet-ui
            -repo=us-docker.pkg.dev/trisa/rvasp-evil
            -repo=us-docker.pkg.dev/trisa/rvasp-bob
            -repo=us-docker.pkg.dev/trisa/rvasp-alice
            -repo=us-docker.pkg.dev/trisa/demo-npm
            -repo=us-docker.pkg.dev/trisa/demo-bff
            -repo=us-docker.pkg.dev/trisa/docs-redirect
            -repo=us-docker.pkg.dev/trisa/testnet-docs
            -repo=us-docker.pkg.dev/trisa/trisads
            -repo=us-docker.pkg.dev/trisa/dsweb
            -grace=2160h
            -keep=16
            -dry-run=True